### ISSUE TITLE
Error message appearing when opening/closing folds

### ISSUE THREAD

**Issue by romgrk** [kevinhwang91/nvim-ufo#10]
### Neovim version (nvim -v | head -n1)

0.8.0-dev

### Operating system/version

archlinux

### How to reproduce the issue

Not sure, need to open/close folds a few times.

### Expected behavior

No error message.

### Actual behavior

![image](https://user-images.githubusercontent.com/1423607/174468008-092da198-7eff-4928-99bf-5277241bf401.png)

**Comment by kevinhwang91** [comment]
Lsp provider? What's server and client

**Comment by kevinhwang91** [comment]
https://github.com/kevinhwang91/nvim-ufo/blob/cf7dc7fa196dbb835a1b8bbc5d7c5f6d786f41ee/lua/ufo/fold/buffer.lua#L142 looks like your config issue?

**Comment by romgrk** [comment]
> looks like your config issue?

 Got it, fixed. The readme could show an actual copy/pastable example for the config, would be more convenient for users.
