### ISSUE TITLE
How can set Ufo virtual text highlight?

### ISSUE THREAD

**Issue by JuanZoran** [kevinhwang91/nvim-ufo#101]
### Neovim version (nvim -v | head -n1)

NVIM v0.9

### Operating system/version

Ubuntu 22.04

### How to reproduce the issue

nop

### Expected behavior

changing the highlight

### Actual behavior

I didn't found Ufo highlight group for virtual text

**Comment by kevinhwang91** [comment]
Not sure what highlight you expected. Need more details.

**Comment by JuanZoran** [comment]
sorry for my ambiguous statements, what I want to set is about **''  %d ''** highlight

**Comment by kevinhwang91** [comment]
https://github.com/kevinhwang91/nvim-ufo/blob/4d10f5fe4ac42c2e23b914ab21db9cce7b5e534e/README.md#L350

**Comment by JuanZoran** [comment]
Thank you for that
