### ISSUE TITLE
The highlight of the folded line is covered by CursorLine

### ISSUE THREAD

**Issue by rockyzhang24** [kevinhwang91/nvim-ufo#103]
### Neovim version (nvim -v | head -n1)

NVIM v0.9.0-dev-667+gdd200db98

### Operating system/version

macOS 13.1

### How to reproduce the issue

1. Fold a piece of code. At this time, the highlight of the folded line is covered by CursorLine.
2. Move the cursor up/down. The folded line is highlighted by UfoFoldedFg/Bg as expected.
3. Move the cursor back. The highlight is covered by CursorLine again.

### Expected behavior

The highlight of the folded line should not be covered by CursorLine when
1. the cursor has not moved away after folding, and
2. the cursor moves back to the folded line

**Comment by kevinhwang91** [comment]
It's Vim behavior, not a bug for ufo, but can be an enhancement.

**Comment by rockyzhang24** [comment]
Nice, bro. You're always the best.

**Comment by kevinhwang91** [comment]
![image](https://user-images.githubusercontent.com/17562139/213927821-6ed6b291-2720-4491-814b-fa32d497e977.png)
`hi UfoCursorFoldedLine guifg=#abb2bf guibg=#342e4f gui=bold,italic`

**Comment by itsuki0927** [comment]
![image](https://github.com/kevinhwang91/nvim-ufo/assets/40518195/af6cfdbf-8433-4488-a295-baae18dc0df8)
I've recently encountered this problem, how can I solve it?
