### ISSUE TITLE
how to disable formatting?

### ISSUE THREAD

**Issue by okuma10** [kevinhwang91/nvim-ufo#104]
### Feature description

Hi,
how can I disable the UFO's text formatting of folded line. I use `pretty fold` for formatting folds , and want to use that as my rendering of folds.

### Describe the solution you'd like

setup `ufo` with `pretty-fold`

**Comment by kevinhwang91** [comment]
https://github.com/kevinhwang91/nvim-ufo/issues/33#issuecomment-1176114936
