### ISSUE TITLE
Indent guidelines from `indent-blankline.nvim` hidden for folds

### ISSUE THREAD

**Issue by UtkarshVerma** [kevinhwang91/nvim-ufo#105]
### Neovim version (nvim -v | head -n1)

NVIM v0.8.2

### Operating system/version

Arch Linux

### How to reproduce the issue

Normal behaviour, here are the configuration options I used for both the plugins.

```lua
  {
    "lukas-reineke/indent-blankline.nvim",
    opts = function(_, opts)
      return vim.tbl_deep_extend("force", opts, {
        char = "▏",
        context_char = "▏",
        char_priority = 40,
        show_current_context = true,
      })
    end,
  },
  {
    "kevinhwang91/nvim-ufo",
    event = "BufReadPost",
    dependencies = { "kevinhwang91/promise-async", "nvim-treesitter/nvim-treesitter" },
    init = function()
      vim.o.foldcolumn = "0" -- Don't show the foldcolumn
      vim.o.foldlevel = 99 -- Using ufo provider need a large value, feel free to decrease the value
      vim.o.foldlevelstart = 99
      vim.o.foldenable = true
    end,
    opts = {
      provider_selector = function()
        return { "treesitter", "indent" }
      end,
    },
  },
```

### Expected behavior

Indent guidelines should not be hidden for the folds.

### Actual behavior

![image](https://user-images.githubusercontent.com/31820255/215318635-c782ee3c-9300-4d04-b19a-6576c81d317b.png)

**Comment by kevinhwang91** [comment]
Search issue by yourself.

**Comment by UtkarshVerma** [comment]
@kevinhwang91 I have already searched that issue and increased the priority of the characters in the config I pasted above. But it did not fix it. Could you please reopen this?

**Comment by UtkarshVerma** [comment]
I can isolate the issue to `show_current_context = true` option in the blankline plugin. If I have it as false, then the guidelines are displayed.

**Comment by kevinhwang91** [comment]
RTFM of indent-blankline.nvim, have another priority for that.

**Comment by kevinhwang91** [comment]
Look like a bug for indent-blankline.nvim
