### ISSUE TITLE
Minimum lines

### ISSUE THREAD

**Issue by kiyoon** [kevinhwang91/nvim-ufo#108]
### Feature description

I almost never want to fold just 1 line. So I set `vim.o.foldminlines = 15`. With this I still see the fold buttons, and if I click those or fold using `za` it folds the larger context. With Treesitter folding it worked.

https://user-images.githubusercontent.com/12980409/215920383-7208a0bb-6ae3-4d2e-8a65-feb334917cb8.mp4

### Describe the solution you'd like

Respect the option value.

**Comment by kevinhwang91** [comment]
Do you want to hide the icon in foldcolumn less than `foldminlines` ?

**Comment by kiyoon** [comment]
Yes, that's what I want.

**Comment by kiyoon** [comment]
Thanks for the really quick fix. Works really well now!
