### ISSUE TITLE
UFO auto closes all folds (zM) on text change

### ISSUE THREAD

**Issue by ziontee113** [kevinhwang91/nvim-ufo#11]
### Neovim version (nvim -v | head -n1)

0.7

### Operating system/version

Arch Linux

### How to reproduce the issue

https://user-images.githubusercontent.com/102876811/174476410-87af1302-71de-47bc-bc1d-b0bb4cefdb89.mp4

### Expected behavior

I want to open / close my folds manually.

### Actual behavior

It closes all folds when the text change.

**Comment by kevinhwang91** [comment]
https://github.com/kevinhwang91/nvim-ufo/issues/7

It's easily solved by saving `foldlevel` before `zR` and restoring after. I am considering add an action for that.

**Comment by ziontee113** [comment]
Thanks for the plugin :)

**Comment by sainttttt** [comment]
I'm having this same issue and nothing seems to fix it. Any text change auto closes everything.
