### ISSUE TITLE
How can I hide these extra markers?

### ISSUE THREAD

**Issue by whxcode** [kevinhwang91/nvim-ufo#112]
### Neovim version (nvim -v | head -n1)

NVIM v0.9.0

### Operating system/version

macOs Version 13.1 (22C65)

### How to reproduce the issue

How can I hide these extra markers?

<img width="1800" alt="image" src="https://user-images.githubusercontent.com/44012914/216525692-1345f356-3603-4d59-9928-ecf6633f0349.png">

### Expected behavior

How can I hide these extra markers?

### Actual behavior

How can I hide these extra markers?

**Comment by kevinhwang91** [comment]
https://github.com/kevinhwang91/nvim-ufo/issues/4#issuecomment-1407651217

**Comment by whxcode** [comment]
> [#4 (comment)](https://github.com/kevinhwang91/nvim-ufo/issues/4#issuecomment-1407651217)

thanks
