### ISSUE TITLE
UnhandledPromiseRejction error on buffer load

### ISSUE THREAD

**Issue by ziontee113** [kevinhwang91/nvim-ufo#12]
### Neovim version (nvim -v | head -n1)

0.7

### Operating system/version

Arch Linux

### How to reproduce the issue

- When loading a new buffer

### Expected behavior

- No Errors

### Actual behavior

![Screenshot from 2022-06-19 17-32-59](https://user-images.githubusercontent.com/102876811/174476754-9c2c3f13-c43c-47ff-bbce-78db6f0a7264.png)

**Comment by kevinhwang91** [comment]
What's client? coc.nvim or nvim lsp?
What's server?

**Comment by ziontee113** [comment]
I'm using nvim lsp. Sumneko Lua is the server. Sorry for not mentioning that before.

**Comment by kevinhwang91** [comment]
Should fix now, update code please.

**Comment by ziontee113** [comment]
Thanks, no more of those errors :)
