### ISSUE TITLE
How to make the gutter icons looks like in readme

### ISSUE THREAD

**Issue by Aneeqasif** [kevinhwang91/nvim-ufo#120]
### Feature description

so this how my current config looks like there are some things that i dont know how to configure being new to neovim 
![image](https://user-images.githubusercontent.com/78728701/227482450-6db04a2c-e7dc-40b5-bead-a81dda21c239.png)

1- how can i make those `+` , `-` icons looks like arrows as u showed
2- how can i make the background of preview window a bit light or darker , i dont want to apply a specific color cz i have to reconfigure it each time i change colorsheme so if it changes dynamically with colorscheme it will be ideal
3- make the background color of thin line behin + and - symbols in left side gutter of neovim the normal default background insread of the light background

**Comment by rockyzhang24** [comment]
1. Please check this pinned issue https://github.com/kevinhwang91/nvim-ufo/issues/4
2. To change the highlights of the preview window, you should use `winhighlight`. For example:
```lua
ufo.setup({
  preview = {
    win_config = {
      winhighlight = 'Normal:Normal',
    },
  },
})
```
Regarding how to config `winhighlight`, please see `:h 'winhighlight'`.
However, (neo)vim can not change highlights dynamically. To set a highlight, either define a new highlight group or link to an existing one. See `:h highlight`.
3. Set this `FoldColumn` highlight group. See `:h nvim_set_hl()`.
