### ISSUE TITLE
do not fold on <esc>

### ISSUE THREAD

**Issue by jfmoulin** [kevinhwang91/nvim-ufo#124]
### Feature description

Maybe I missed something but:

I would like to avoid the folds closing after an edit when I type an escape.

I am editing python code and every ESC closes all folds, I usually have to make more than one edit per block ;0)

### Describe the solution you'd like

an option to (de)activate folding upon ESC after an edit (i.e going from insert to normal mode)

**Comment by kevinhwang91** [comment]
RTFM

**Comment by jfmoulin** [comment]
I tried ;0)
I'll try again, now that I know it should be possible.
Anways, thanks for the nice plugin.

**Comment by s1n7ax** [comment]
At

There is an explanation here:
https://github.com/kevinhwang91/nvim-ufo?tab=readme-ov-file#usage

Solution is to add keymaps here:
https://github.com/kevinhwang91/nvim-ufo?tab=readme-ov-file#customize-configuration
