### ISSUE TITLE
can't fold using LSP with yaml file.

### ISSUE THREAD

**Issue by hungvx-dev** [kevinhwang91/nvim-ufo#128]
### Neovim version (nvim -v | head -n1)

Nvim 0.9

### Operating system/version

macOS Ventura

### How to reproduce the issue

When opening a YAML file, an error occurs: 
<img width="1372" alt="image" src="https://user-images.githubusercontent.com/85088954/235303767-1ad77f11-82f2-4573-b3e5-319ed538efe6.png">

This is my config: 
<img width="616" alt="image" src="https://user-images.githubusercontent.com/85088954/235303831-441cf2ec-281b-470b-a7cb-edebb25980b1.png">
<img width="428" alt="image" src="https://user-images.githubusercontent.com/85088954/235303851-992e4363-1880-460b-a9a0-5735b1cf2075.png">

### Expected behavior

none

### Actual behavior

none

**Comment by kevinhwang91** [comment]
https://github.com/kevinhwang91/nvim-ufo/issues/127

**Comment by hungvx-dev** [comment]
@kevinhwang91  Thank you. I fixed it. 

<img width="633" alt="image" src="https://user-images.githubusercontent.com/85088954/235334107-67ca5cfc-5d92-4e3a-b523-bc94161dcbcc.png">

Set folding after when getting capabilities from cmp

**Comment by seanturner026** [comment]
Sharing the solution in text for anyone else who finds their way here:

```lua
capabilities.textDocument.foldingRange = {
    dynamicRegistration = false,
    lifeFoldingOnly = true,
}
```
