### ISSUE TITLE
Add option to get virtual text of the end fold line.

### ISSUE THREAD

**Issue by kamack38** [kevinhwang91/nvim-ufo#130]
### Feature description

This feature would allow users to apply syntax highlighting to the end fold line.

### Describe the solution you'd like

```lua
local handler = function(virtTextStart, virtTextEnd, ...)
...
end
```

**Comment by kevinhwang91** [comment]
`enable_get_fold_virt_text`

https://github.com/kevinhwang91/nvim-ufo/blob/9e829d5cfa3de6a2ff561d86399772b0339ae49d/doc/example.lua#L172-L182

**Comment by kamack38** [comment]
Thank you very much!
