### ISSUE TITLE
The fold text of the same buffer is displayed in two different windows

### ISSUE THREAD

**Issue by lu5je0** [kevinhwang91/nvim-ufo#131]
### Neovim version (nvim -v | head -n1)

NVIM v0.9.0

### Operating system/version

macOS 13.3.1

### How to reproduce the issue

`cat mini.lua`
```lua
-- Use Vim packages install the plugin, also work with some plugins manager such as packer.nvim
vim.o.packpath = '~/.local/share/nvim/site'
vim.cmd('packadd promise-async')
vim.cmd('packadd nvim-ufo')

-- Setting
vim.o.foldcolumn = '1'
vim.o.foldlevel = 99
vim.o.foldlevelstart = -1
vim.o.foldenable = true

local ufo = require('ufo')
ufo.setup()
vim.keymap.set('n', 'zR', ufo.openAllFolds)
vim.keymap.set('n', 'zM', ufo.closeAllFolds)
```
`nvim --clean +'so mini.lua'`

1.
2.
3.
...

### Expected behavior

The fold text is only displayed in the window that closes the fold.

### Actual behavior

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/17700877/236512578-576ae9de-ea3d-4f5f-9766-1b4634abfd8a.png">

**Comment by kevinhwang91** [comment]
It's the limitation of ufo.  To render folded lines use extmark which is buffer related. No way to make the same buffer with different extmarks.

**Comment by vurentjie** [comment]
sure perhaps you can wait for `nvim_win_set_extmark` to be implemented here: https://github.com/neovim/neovim/issues/19654

**Comment by kevinhwang91** [comment]
nightly with the latest codebase of ufo should work.
