### ISSUE TITLE
In the nvim 0.9 version, after using zc to open the fold, the fold text occasionally does not disappear.

### ISSUE THREAD

**Issue by lu5je0** [kevinhwang91/nvim-ufo#132]
### Neovim version (nvim -v | head -n1)

NVIM v0.9.0

### Operating system/version

macOS 13.3.1

### How to reproduce the issue

`cat mini.lua`
```lua
-- Use Vim packages install the plugin, also work with some plugins manager such as packer.nvim
vim.o.packpath = '~/.local/share/nvim/site'
vim.cmd('packadd promise-async')
vim.cmd('packadd nvim-ufo')

-- Setting
vim.o.foldcolumn = '1'
vim.o.foldlevel = 99
vim.o.foldlevelstart = -1
vim.o.foldenable = true

local ufo = require('ufo')
ufo.setup()
vim.keymap.set('n', 'zR', ufo.openAllFolds)
vim.keymap.set('n', 'zM', ufo.closeAllFolds)
```
`nvim --clean +'so mini.lua'`

1.
2.
3.
...

### Expected behavior

After opening the fold with zc, the fold text should be removed immediately.
<img width="484" alt="image" src="https://user-images.githubusercontent.com/17700877/236513577-ab9f02a2-6601-439e-a832-61b8bf6dd01b.png">

### Actual behavior

<img width="537" alt="image" src="https://user-images.githubusercontent.com/17700877/236513528-583b6f1d-e775-4c6b-afe0-dfa73d67fa03.png">

**Comment by rockyzhang24** [comment]
I cannot reproduce this issue. Btw, `zc` is to close a fold not open, so do you mean `zo`?

**Comment by kevinhwang91** [comment]
I know this issue for a long time. To open a fold in a clean ENV like nvim in docker,  `open_fold_hl_timeout` won't work. We can't reproduce because of our neovim have redrawed in some reasons.

**Comment by lu5je0** [comment]
Thanks!
