### ISSUE TITLE
Add folding to arrays

### ISSUE THREAD

**Issue by TiLopes** [kevinhwang91/nvim-ufo#135]
### Feature description

In VSCodium you are able to fold an array:
|Before:   |After:   |
|---|---|
|![image](https://github.com/kevinhwang91/nvim-ufo/assets/106965010/d02cfbe5-a792-4302-91f1-752286b5c60f)|![image](https://github.com/kevinhwang91/nvim-ufo/assets/106965010/5fb5da2e-8b2e-4a2b-95f3-87bc69107b49)|

However when doing the same in neovim with this plugin it simply folds the top level folding option:
|Before:   |After:   |
|---|---|
|![image](https://github.com/kevinhwang91/nvim-ufo/assets/106965010/a8294e76-33f1-4ca6-9e8f-c3eebda47aaf)|![image](https://github.com/kevinhwang91/nvim-ufo/assets/106965010/791b3a15-0583-4800-98bb-92e60bbb39fa)|

### Describe the solution you'd like

Just fold the elements on the array.

### Additional context

Using LunarVim with this plugin installed.
Fold settings:
![image](https://github.com/kevinhwang91/nvim-ufo/assets/106965010/e78bed5e-d790-4371-b2cc-fbea35d2534f)

nvim-ufo config:
![image](https://github.com/kevinhwang91/nvim-ufo/assets/106965010/62894cdf-7c52-4356-8272-4d201771e6f5)

**Comment by kevinhwang91** [comment]
What's the `filetype` of the buffer?  Does `UfoInspect` output  `Selected provider: lsp`?
