### ISSUE TITLE
Turnoff automatic folds

### ISSUE THREAD

**Issue by kaddkaka** [kevinhwang91/nvim-ufo#136]
### Feature description

The automatic fold is scary and makes things "jump around" as if alive, especially the automatic close of folds is something I want to avoid. I would prefer to create/open/close them manually.

I'm really just interested in getting folds to include the newline just before the fold, such that:
```
# Banana
  Some say this isn't even a fruit.
  Usually yellow.
# Apple
  Another kind of fruit.
```
Can fold into
```
# Banana ⋯
# Apple ⋯
```
With preserved syntax highlight for the unfolded `# Banana` part.

### Describe the solution you'd like

Manual folding where the folded text does not occupy it's own line but rather just a few characters on the previous line.

If it's not configurable with ufo, what part of the code should I study to roll this behavior by myself?

**Comment by kevinhwang91** [comment]
https://github.com/kevinhwang91/nvim-ufo/issues/125 is what you should review.

**Comment by kaddkaka** [comment]
@kevinhwang91 Sorry I'm not sure I could find anything of relevance. The folds are correct with indent provider - I just don't want them to be automatic.

**Comment by kevinhwang91** [comment]
https://github.com/kevinhwang91/nvim-ufo/blob/45aede6f5c4981156df3ddeeae01c4290e43e104/doc/example.lua#L15

**Comment by realtica** [comment]
Same here, please I do not understand why the folding is automatic..
This is an amazing plugin but we need to Manual folding.
