### ISSUE TITLE
How to unhighlight collapsed lines

### ISSUE THREAD

**Issue by renjinxi** [kevinhwang91/nvim-ufo#140]
### Feature description

When there are too many collapsed lines highlighted, it will show a particularly messy

### Describe the solution you'd like

Only the identifier at the end of the line is highlighted

**Comment by renjinxi** [comment]
![企业微信截图_16884345796383](https://github.com/kevinhwang91/nvim-ufo/assets/48796935/e50b0f16-c48c-43a7-9768-ac59e603f4ed)
Just like above, only the last part is highlighted

**Comment by kevinhwang91** [comment]
Why the last is highlighted? The cursor is under the`zipfile|`.

**Comment by renjinxi** [comment]
> Why the last is highlighted? The cursor is under the`zipfile|`.

<img width="982" alt="image" src="https://github.com/kevinhwang91/nvim-ufo/assets/48796935/49eecdad-f4b1-4931-98db-dec7e4966aa6">
When the code collapses, highlight only the ellipsis at the end of the collapsed line，The folding effect above is from Pycharm， I don't know how to do that in nvim-ufo

**Comment by rockyzhang24** [comment]
So ugly. Highlightings only on the last parts are much like the patches on your pants. On the contrary, highlighting the whole line is quite pretty (like wearing a striped shirt, but the premise is picking a matching color) and straightforward. You could recognize which lines are folded without moving your eyeballs, especially on a long line. This requirement is too specific and bizarre, and I think you could fork the repo and tweak it by yourself.

**Comment by renjinxi** [comment]
> So ugly. Highlightings only on the last parts are much like the patches on your pants. On the contrary, highlighting the whole line is quite pretty (like wearing a striped shirt, but the premise is picking a matching color) and straightforward. You could recognize which lines are folded without moving your eyeballs, especially on a long line. This requirement is too specific and bizarre, and I think you could fork the repo and tweak it by yourself.

You also said that highlighting entire lines is especially noticeable when you have lots of folds and split the screen, so you know how disastrous it is

**Comment by renjinxi** [comment]
The meaning of folding itself is to hide information, and it should not attract too much attentio

**Comment by renjinxi** [comment]
> So ugly. Highlightings only on the last parts are much like the patches on your pants. On the contrary, highlighting the whole line is quite pretty (like wearing a striped shirt, but the premise is picking a matching color) and straightforward. You could recognize which lines are folded without moving your eyeballs, especially on a long line. This requirement is too specific and bizarre, and I think you could fork the repo and tweak it by yourself.

I don't want to argue with anyone, I just don't know how to undo this fold highlight, and I'd appreciate it if you could tell me what to do instead

**Comment by rockyzhang24** [comment]
Nope. I like the style, highlighting the whole line. Noticeable appearance is essential for showing the folded line. Folding is to hide info, so we need to show the line distinctively noting that the detailed info is hidden. If merely the last part is marked, it is hard to distinguish whether some lines are folded, or unfinished code is left there. 

Like I said, this requirement is too specific and subjective. The best way to meet your need is forking it and changing it.

**Comment by rockyzhang24** [comment]
<img width="1728" alt="image" src="https://github.com/kevinhwang91/nvim-ufo/assets/11582667/c6f6f9ef-d245-48ce-be17-5d46d14a8140">

I have to say it is so pretty!

**Comment by renjinxi** [comment]
![image](https://github.com/kevinhwang91/nvim-ufo/assets/48796935/21f9011e-4c49-4a57-89c2-78d00db8f79c)
![image](https://github.com/kevinhwang91/nvim-ufo/assets/48796935/9f385906-71e8-49c1-893c-76b2817f8f70)
This is unacceptable to me, but thanks for the reply, I know what to do

**Comment by kevinhwang91** [comment]
```
hi Folded guifg=NONE guibg=NONE
hi UfoFoldedEllipsis guibg=yellow
```
