### ISSUE TITLE
Chamge icon

### ISSUE THREAD

**Issue by karambaq** [kevinhwang91/nvim-ufo#144]
### Neovim version (nvim -v | head -n1)

NVIM v0.10.0-dev-601+gd55d7646c

### Operating system/version

macOS 13.2.1

### How to reproduce the issue

<img width="1411" alt="image" src="https://github.com/kevinhwang91/nvim-ufo/assets/14233969/5f60dda4-2225-4b47-8e99-ee6821cc55f4">

### Expected behavior

I'm using nerd font, all icons are show except this one, how can I customize just the icon?a

### Actual behavior

Icon not showing

**Comment by rockyzhang24** [comment]
Can't reproduce. I think this is not a bug of ufo.
Nerd font was upgraded to v3 version and many icons' codepoints were changed.

**Comment by karambaq** [comment]
I’m using the last version of the font from nerd-fonts. However, It’s not the bug with ufo, I just wanted to know how can I fix it using different icon.

**Comment by rockyzhang24** [comment]
See https://github.com/kevinhwang91/nvim-ufo#customize-fold-text please

**Comment by karambaq** [comment]
Seems like a lot of code to just change an icon, thank you :)

**Comment by rockyzhang24** [comment]
No exactly. The example shows how to customize the whole virtual text, not just the icon. In your case, you just need to change the `suffix` and use the old `virtText`.  The code will be quite short. 

Btw, are you using a neovim distribution like Lunarvim, or your own neovim config?

**Comment by karambaq** [comment]
I'm using Astronvim
