### ISSUE TITLE
How to fold/unfold current line

### ISSUE THREAD

**Issue by Pezhvak** [kevinhwang91/nvim-ufo#147]
### Feature description

I'm sorry to create an issue for this, but i cannot figure it out, 

`zM` az `zR` folds and unfolds all the lines, i want to create a keymap to fold and unfold current line, like the arrows does in the foldcolmun.

also, thank you for this repo 👍🏻 

### Describe the solution you'd like

an internal command or a workaround to have the arrow functionality in the foldcolumn executable with a keyboard shortcut.

**Comment by kevinhwang91** [comment]
`h foldopen` `h foldclose` `h foldclosed()`
