### ISSUE TITLE
Configurable suffix for the default virtual text handler

### ISSUE THREAD

**Issue by MariaSolOs** [kevinhwang91/nvim-ufo#151]
### Feature description

Amazing plugin!
I just have a small request: I don't want full-blown control over the virtual text that's displayed, I just want to change the 3 dots to a different string.

### Describe the solution you'd like

Add a setting to make [this suffix](https://github.com/kevinhwang91/nvim-ufo/blob/0c0e1e0af68a608b15d18125be92953c553a5f27/lua/ufo/decorator.lua#L238) configurable. This can be a new option, or the existing `fold_virt_text_handler` can also be expanded to be a string, and if so, then the default handler is used using that value as the suffix.

**Comment by kevinhwang91** [comment]
https://github.com/kevinhwang91/nvim-ufo/issues/99

It's a redundant option and makes users confused to customize ufo. And the `README` and `example.lua` have given the code to work. 

It sounds ruthless, but it reduces the maintenance burden for me.

**Comment by MariaSolOs** [comment]
@kevinhwang91 I understand. Thank you for your time and I apologize for the duplicate issue.
