### ISSUE TITLE
Customize folding using different source

### ISSUE THREAD

**Issue by ray-x** [kevinhwang91/nvim-ufo#16]
### Feature description

Would be great to provide an API and allow the binding of different folding expressions.  One scenario is a very large (auto-generated) code (100k ~ 200k LOC per file) I am using.

### Describe the solution you'd like

e.g.
```lua
if filetype = 'go' then
  if  filesize < 6M then
   api.nvim_win_set_option(current_window, 'foldexpr', 'ufo#foldexpr()')
  elseif  filesize < 10M then
   api.nvim_win_set_option(current_window, 'foldexpr', 'tsfold#foldexpr()')
  else
   api.nvim_win_set_option(current_window, 'foldexpr', 'tsfold#foldexpr()')
  end
end
if filetype = 'lua' then
  api.nvim_win_set_option(current_window, 'foldexpr', 'treesitter#foldexpr()')
end
```

**Comment by kevinhwang91** [comment]
keep your other fold expr and use `provider_selector` to disable ufo when you want.

https://github.com/kevinhwang91/nvim-ufo/blob/a11c899ae12cc66b2d7f1c7bc99c506a5db113eb/doc/example.lua#L3-L18

**Comment by ray-x** [comment]
well, I find the disable is not really working for me
```lua
  -- only enable for following filetypes
  local whitelist = {
    ["gotmpl"] = "indent",
    ["python"] = "lsp",
    ["html"] = "indent",
  }
  require("ufo").setup({
    fold_virt_text_handler = handler,
    provider_selector = function(bufnr, filetype)
      if whitelist[filetype] then
        return whitelist[filetype]
      end
      return ""  -- everything not listed in whitelist should be disabled
    end,
  })
```

When I edit lua code, ufo still enabled.

**Comment by kevinhwang91** [comment]
can't reproduce.
Run `UfoInspect`, will output:
```log
Buffer: 19
Fold Status: start
Main provider: 
Selected provider: nil
```

**Comment by ray-x** [comment]
<img width="340" alt="image" src="https://user-images.githubusercontent.com/1681295/174561233-2d78042e-55ad-4a6f-ac20-cc39d1b6567a.png">
From the screen shot, I think ufo is disabled in config but not disable when I press `za/zm`

**Comment by kevinhwang91** [comment]
If `selected provider` is set after the foldingRanges come back, make sure the folds are applied by ufo.
No idea why your remap `za/zm` will make ufo request folding. Make sure that your `foldmethod` value is expected. The window opt will be inherent as unexpected.
You can enable debug mode by `UFO_LOG=debug nvim` and tail log `tail -f ~/.cache/nvim/ufo.log`

**Comment by kevinhwang91** [comment]
Do you mean disable virtual text? I can't see any data returned by providers from the log and your image.

**Comment by ray-x** [comment]
The setup :    `fold_virt_text_handler = handler,`
But if ufo is not enabled, will virtual_text enable?

**Comment by kevinhwang91** [comment]
no selector ufo still enables virtual text. need detach. use `UfoDetach` and reset your `foldtext` option.
If a buffer is detached,  ufo does nothing for the buffer (only for the detached buffer).
Disable will disable all features.

**Comment by ray-x** [comment]
ok, that make sense.
