### ISSUE TITLE
How to change or remove the color of the folded line?

### ISSUE THREAD

**Issue by MichaelC001** [kevinhwang91/nvim-ufo#164]
### Feature description

How to change or remove the color of the folded line?

### Describe the solution you'd like

I'd like to change the color of the folding text line

**Comment by kevinhwang91** [comment]
https://github.com/kevinhwang91/nvim-ufo/blob/6f2ccdf2da390d62f8f9e15fc5ddbcbd312e1e66/doc/example.lua#L129-L170
