### ISSUE TITLE
vim.treesitter.query.get_query() is deprecated

### ISSUE THREAD

**Issue by georgeharker** [kevinhwang91/nvim-ufo#175]
### Neovim version (nvim -v | head -n1)

NVIM 0,9.4

### Operating system/version

MacOS and linux

### How to reproduce the issue

fire up nvim on a file which uses folding

```
vim.treesitter.query.get_query() is deprecated, use vim.treesitter.query.get() instead. :help deprecated                                   
This feature will be removed in Nvim version 0.10                                                                                          
```

It looks like others like telescope have fixed this with a check

eg

https://github.com/nvim-telescope/telescope.nvim/commit/359e9ffc74511c1afaf744cf705819cac90d8ed3

### Expected behavior

no deprecation warning

### Actual behavior

deprecation warning issued

**Comment by rockyzhang24** [comment]
I can’t reproduce it either.

**Comment by georgeharker** [comment]
Strange. I’ll do some digging. I suspect this will come up sooner or later as binaries get updated as other projects had to do this. But perhaps it’s a very recent change
