### ISSUE TITLE
Restrict virtual text to local window folds

### ISSUE THREAD

**Issue by ReubenM** [kevinhwang91/nvim-ufo#178]
### Neovim version (nvim -v | head -n1)

0.9.4

### Operating system/version

Linux

### How to reproduce the issue

When defining a custom fold text function, the winnr is not passed as an argument to allow matching against current active window, so virtual text shows up in all windows with the same buffer, even though the folding is local to the window.

### Expected behavior

Fold virtual text is applied locally to a buffer's windows where lines are folded.

### Actual behavior

Fold virtual text is applied globally to a buffer's windows based on which lines are folded in the currently active window.

**Comment by kevinhwang91** [comment]
Extmark is buffer local scope.
https://github.com/kevinhwang91/nvim-ufo/issues/131#issuecomment-1807188169
