### ISSUE TITLE
Folds opened by `za` or `zo` close recursively when leaving insertmode

### ISSUE THREAD

**Issue by ranjithshegde** [kevinhwang91/nvim-ufo#18]
### Neovim version (nvim -v | head -n1)

NVIM v0.8.0-dev+452-gb2ed439bd5

### Operating system/version

Linux  5.18.5-arch1-1 #1 SMP PREEMPT_DYNAMIC (arch linux)

### How to reproduce the issue

```lua
local function level1()
    local function level2()
        |
    end
end
```
1. Place cursor on line 2 `local function level2()`
2. Press either `za` (toggle fold under cursor) or `zo` (open fold under cursor)
3. Do edits in insert mode and hit `<esc>` to go to normal mode
...

### Expected behavior

```lua
local function level1()
    local function level2()
        -- whatever edits I made
    end
end
```
Folds under the cursor that are opened manually with `za` or `zo` remain open (so that i can inspect what I just changed, or any other purpose)

### Actual behavior

all folds have been closed
```lua
local function level1() -- folds here
end
```

**Comment by xiyaowong** [comment]
this is nvim's expected behavior.  `:h foldlevel` `foldlevelstart`

**Comment by kevinhwang91** [comment]
You should increase the foldlevel and trace the value after you go back normal mode `verb set foldlevel`

**Comment by ranjithshegde** [comment]
Sorry for my ignorance, but how do I do that? shouldnt `za` or `zo` do that automatically?

**Comment by kevinhwang91** [comment]
`set foldlevel=99 foldlevelstart<`

**Comment by ranjithshegde** [comment]
> `set foldlevel=99 foldlevelstart=-1`

This fixes the collapse problem but all folds are always open until I manually close them, even at `BufEnter`

**Comment by xiyaowong** [comment]
You can create some autocmds to implement your requirements, but these are not related to this plugin

**Comment by kevinhwang91** [comment]
> > `set foldlevel=99 foldlevelstart=-1`
> 
> This fixes the collapse problem but all folds are always open until I manually close them, even at `BufEnter` also `require("ufo").closeAllFolds()` has no affect until I first manually close all folds

Create folds is async, your event can't work is expected. I think you should write the function yourself. It's not the normal workflow, sorry.

**Comment by ranjithshegde** [comment]
> Create folds is async, your event can't work is expected. I think you should write the function yourself. It's not the normal workflow, sorry.

I understand that this might not be the plugin focus, but using `za` or `zo` which is basically opening a specifc fold (also what you do in your intro video, just with mouse) is a very common workflow.

But I fully appreciate if you dont want to support this. I will give it a shot.

thanks for the plugin and the excellent work!

**Comment by ranjithshegde** [comment]
> Every time update folding, vim respect the fold level. I suggest you set the value as large enough, otherwise, it's buggy for ufo while you are editing buffer because the level may change a lot.

Are you referring to `foldlevelstart`?

**Comment by kevinhwang91** [comment]
No, `foldlevel`, you should RTFM before customizing or hacking any plugins.
