### ISSUE TITLE
Crash on vsplit on large file (1k lines)

### ISSUE THREAD

**Issue by serranomorante** [kevinhwang91/nvim-ufo#180]
### Neovim version (nvim -v | head -n1)

nvim 0.10... dev

### Operating system/version

arch linux

### How to reproduce the issue

Same as [#176](https://github.com/kevinhwang91/nvim-ufo/issues/176)

![t-rec_35](https://github.com/kevinhwang91/nvim-ufo/assets/43413954/3c30cd69-6e08-499f-bd97-5872db88c442)

# Steps

1. open [this](https://pastebin.com/raw/1fu68PbD) file
2. fold everything with zM
3. vsplit
4. start to open folds

### Expected behavior

don't crash

### Actual behavior

crash

**Comment by rockyzhang24** [comment]
On my end, it doesn't crash. But I encountered another issue (https://github.com/kevinhwang91/nvim-ufo/issues/181). Not sure if it's related to this issue.

https://github.com/kevinhwang91/nvim-ufo/assets/11582667/923f6890-e15f-464e-895e-eda1369767b7

**Comment by serranomorante** [comment]
> On my end, it doesn't crash. But I encountered another issue (https://github.com/kevinhwang91/nvim-ufo/issues/181). Not sure if it's related to this issue.
> 
> https://github.com/kevinhwang91/nvim-ufo/assets/11582667/923f6890-e15f-464e-895e-eda1369767b7

Hi! Thanks

Maybe if you stay on the left window (instead of moving to the split on the right) maybe that should make it crash. (That's the only difference I can see from my example)

I'm using a bare-bones nvim with latest ufo and promise-async and nothing else so I believe this is definitely reproducible.

**Comment by rockyzhang24** [comment]
> Maybe if you stay on the left window (instead of moving to the split on the right) maybe that should make it crash. (That's the only difference I can see from my example)

I set `splitright` in my vimrc so the right window is the new window after `:vsplit`.
