### ISSUE TITLE
Flickering virtual text on the unfolded lines in the split window

### ISSUE THREAD

**Issue by rockyzhang24** [kevinhwang91/nvim-ufo#181]
### Neovim version (nvim -v | head -n1)

NVIM v0.10.0-dev-1627+g879617c9b

### Operating system/version

macOS 14.1.1 (the latest)

### How to reproduce the issue

1. Open any file
2. `zM` to fold all
3. `:vsplit` and then focus on the new window
4. `za` to unfold and then move the cursor downwards/upwards.

The virtual text on the unfolded lines should be gone. However, not only are they still there, but they also keep flickering as the cursor moves upwards/downwards.

I attached a short demo below

https://github.com/kevinhwang91/nvim-ufo/assets/11582667/41dedb90-c8e0-4981-a3e0-3a18f144af05

Thank you very much.

**Comment by wookayin** [comment]
I think this bug still happens (as of 9fa77fb) -- especially when there are more than two windows with different folds open/closed. Possibly related to #187.
