### ISSUE TITLE
Writing to a file opens all folds

### ISSUE THREAD

**Issue by OmarEbrahim1** [kevinhwang91/nvim-ufo#182]
### Neovim version (nvim -v | head -n1)

NVIM v0.9.4

### Operating system/version

Arch Linux AMD64

### How to reproduce the issue

:w in a file with closed folds

### Expected behavior

:w in a file keeps the folds as they are

### Actual behavior

:w in a file opens all folds

**Comment by OmarEbrahim1** [comment]
This is my ufo config:

`vim.o.foldcolumn = '1' -- '0' is not bad
vim.o.foldlevel = 99 -- Using ufo provider need a large value, feel free to decrease the value
vim.o.foldlevelstart = 99
vim.o.foldenable = true

vim.keymap.set('n', 'zR', require('ufo').openAllFolds)
vim.keymap.set('n', 'zM', require('ufo').closeAllFolds)

require("ufo").setup({
  -- your configuration comes here
  -- or leave it empty to use the default settings
  -- refer to the configuration section below
})
`

**Comment by kevinhwang91** [comment]
Your code base is stale, please update the latest.
