### ISSUE TITLE
How to disable the highlight when unfolding a block of code?

### ISSUE THREAD

**Issue by niksingh710** [kevinhwang91/nvim-ufo#185]
### Neovim version (nvim -v | head -n1)

NVIM v0.9.4

### Operating system/version

arch linux

### How to reproduce the issue

just the default config

### Expected behavior

no highlight on unfolding

### Actual behavior

![output](https://github.com/kevinhwang91/nvim-ufo/assets/60490474/72e5192d-da91-417c-8891-7281622f70e6)

**Comment by rockyzhang24** [comment]
Set `open_fold_hl_timeout` to `0`.
