### ISSUE TITLE
[Enhancement] Integrate with indent-blankline.nvim or provide an API for an integration

### ISSUE THREAD

**Issue by akinsho** [kevinhwang91/nvim-ufo#19]
### Feature description

Hi, 

Thanks for your work on this plugin, it's the first time in many years of using (neo)vim that I've ever had normal looking folds 🚀.

One thing that using folds more has re-introduced for me though is the gaps appearing between my indent lines. The plugin https://github.com/lukas-reineke/indent-blankline.nvim fixes this limitation in normal lines by using extmarks to draw the indent lines and cover the gaps that exist in conceal based solutions.

With this plugin enabled, though, these extmarks are no longer visible and folded section introduce gaps between my indent lines.

### Describe the solution you'd like

I don't know how this plugin is designed i.e. extmarks (most likely I think) or floating windows, but I'm wondering if there's some chance of either blending the extmarks not sure if this could work or if it's possible to query for the existing indent lines (extmarks) via `nvim_buf_get_extmarks` and re-apply/add them to the extmarks this plugin creates and if it's via floating window then it should already be working.

If it isn't entirely easy or possible on this side then maybe the author of that plugin would be willing to provide an API to get the indents for a line so they can be prepended to the fold text. I'm happy to ask if you are amenable but I don't really know how this is structured and what approach would make sense

### Additional context

Example in vscode with indents extending beyond folds (I know vscode is rarely 100% applicable, I just meant for reference of what the desired result looks like)

![image](https://user-images.githubusercontent.com/22454918/174607139-db1ef61f-ef23-4ccc-b725-e56039e1251d.png)

### Unfolded indents across blank lines
<img width="625" alt="image" src="https://user-images.githubusercontent.com/22454918/174607311-75e30fe8-8dde-40af-b349-ba3a5e865458.png">

### Current indent lines across folds
<img width="442" alt="image" src="https://user-images.githubusercontent.com/22454918/174607585-e37fa1bb-203c-402d-b60b-c473fa61283e.png">

**Comment by kevinhwang91** [comment]
https://github.com/lukas-reineke/indent-blankline.nvim/blob/6177a59552e35dfb69e1493fd68194e673dc3ee2/lua/indent_blankline/init.lua#L565

greater than 10 will work.

**Comment by akinsho** [comment]
@kevinhwang91 I tried increasing the value all the way up to 50 and that didn't make a difference

**Comment by kevinhwang91** [comment]
Have you updated nvim-ufo after I close this issue?

**Comment by akinsho** [comment]
Oh sorry no I didn't realise you had committed a change

**Comment by kevinhwang91** [comment]
674 line should be changed also.

**Comment by akinsho** [comment]
Ah thanks, after I updated and changed the other line that worked well 👍🏿 I'll raise an issue over there to make the priority configurable thanks.
