### ISSUE TITLE
No text displayed on folded line

### ISSUE THREAD

**Issue by Nunwan** [kevinhwang91/nvim-ufo#190]
### Neovim version (nvim -v | head -n1)

NVIM v0.10.0-dev-813+g5a25dcc5a

### Operating system/version

Archlinux 6.6.7

### How to reproduce the issue

`cat init.lua`
```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({{'kevinhwang91/nvim-ufo', dependencies = 'kevinhwang91/promise-async'}})


-- Setting
vim.o.foldcolumn = '1'
vim.o.foldlevel = 99
vim.o.foldlevelstart = -1
vim.o.foldenable = true

local ufo = require('ufo')
ufo.setup()
vim.keymap.set('n', 'zR', ufo.openAllFolds)
vim.keymap.set('n', 'zM', ufo.closeAllFolds)
```````

`nvim` (I use lazy but other package manager should do the same ?)

1. Open a file
2. fold something (zf5j here)

### Expected behavior

It should display the text of the first line (like that : screenshot taken with version 1.3.0)
![image](https://github.com/kevinhwang91/nvim-ufo/assets/30219092/3d5a6a1f-d871-48fd-9d29-cd7cd2c5fb1c)

### Actual behavior

 the folded line is completely opaque
![image](https://github.com/kevinhwang91/nvim-ufo/assets/30219092/9a97699e-172a-4e84-b824-e82edef1d58e)

My current workaround is using the v1.3.0 but I prefer reporting the bug ! Sorry if it is a duplicate I did not find the same issue as mine. Tell me if it is just a new configuration change that I did not notice !
Thanks for all the good work :)

**Comment by kevinhwang91** [comment]
Update your nightly.

**Comment by Nunwan** [comment]
At the risk of being a noob, can you specify your answer ?

**Comment by Nunwan** [comment]
Forgot that I was on nightly ... Thanks a lot !

**Comment by wllenyj** [comment]
What's mean the nightly ? -_- !

**Comment by wllenyj** [comment]
> What's mean the nightly ? -_- !

I got, the `nightly` mean that is the version of neovim....
