### ISSUE TITLE
Lazyvim installation instruction

### ISSUE THREAD

**Issue by mbaneshi** [kevinhwang91/nvim-ufo#191]
### Feature description

Would you please add lazyvim installation and configuration instructions in readme?

### Describe the solution you'd like

Although Packer and LazyVim are relatively similar, but it is hard for newbies to adopt them   

So it will be benefitial do so .
Thanks in advanced .

### Additional context

https://www.lazyvim.org/

**Comment by dwarfman78** [comment]
Do you have any configuration to share ?

**Comment by mbaneshi** [comment]
What do you mean? Regarding this repo , no I have no chance to utilizing it sincelI have no config yet.

It should be mentioned, I used LazyVim as package manager , and my folding do not work  for unknown reason , I want to use this package because I guess problem is about default configuration, it always pop up error now.
Reading help I find some default relayed to my error , I hope this helps me resolving issue.

**Comment by wookayin** [comment]
First of all, https://github.com/LazyVim/LazyVim is not a package manager but a neovim distro. https://github.com/folke/lazy.nvim is the package manager you'd probably talking about (which LazyVim is also based on).

If you read the README of lazy.nvim, installation instruction would be just straightforward: just add this to your plugin spec:
```
  {
    'kevinhwang91/nvim-ufo',
    dependencies = { 'kevinhwang91/promise-async' },
--    event = 'VeryLazy',   -- You can make it lazy-loaded via VeryLazy, but comment out if thing doesn't work
    init = function()
      vim.o.foldlevel = 99
      vim.o.foldlevelstart = 99
    end,
    config = function()
      require('ufo').setup {
        -- your config goes here
        -- open_fold_hl_timeout = ...,
        provider_selector = function(bufnr, filetype)
          ...
        end,
      }
    end,
  }

```

**Comment by mbaneshi** [comment]
Thank you @wookayin , I really appreciated.
Would you please provide default configuration as well .
I mean some useful sane default,just copy paste and ready to go .
The big problem reside beneath this comment in snippets.
Unfortunately I can't go by myself yet.

**Comment by wookayin** [comment]
Default configuration is just nothing, no config, and it should work:

```
require('ufo').setup {
}
```

**Comment by mbaneshi** [comment]
It works , thank you all of you . ❤️❤️❤️
