### ISSUE TITLE
Synchronise folds in all splits

### ISSUE THREAD

**Issue by Rizhiy** [kevinhwang91/nvim-ufo#193]
### Feature description

Currently, if the same buffer is open in two splits toggling fold in one split won't affect the other split.
This is particularly annoying if virtual text is enabled.
Since virtual text is always shared between splits, as long as one split has the fold open virtual text will be shown.

### Describe the solution you'd like

If I open fold in one split, it should also open in all other splits.

**Comment by kevinhwang91** [comment]
Please use nightly. It will use the new `foldtext` feature to render fold text.
