### ISSUE TITLE
Fold arrow shows when collapsed / closed, but when opened it shows nothing

### ISSUE THREAD

**Issue by GitMurf** [kevinhwang91/nvim-ufo#195]
### Neovim version (nvim -v | head -n1)

nvim 0.9.5

### Operating system/version

windows 11

### How to reproduce the issue

Out of the box config

### Expected behavior

I expected to see the fold arrows on lines that can be folded when they are expanded so that I know where all the fold markers are and can click to fold with the mouse if I want to or just use the keymaps.

### Actual behavior

When I fold something for example with za it will fold the area and show the closed arrow which is expected. But then when i open the fold, the arrow disappears as if the fold is gone.

**Comment by GitMurf** [comment]
Here is what it looks like when folded

![image](https://github.com/kevinhwang91/nvim-ufo/assets/64155612/6b45865a-e6e1-40e8-9a6b-e701baa29e0b)

Here is what it looks like after I unfold it (no arrow or sign there is a fold available)

![image](https://github.com/kevinhwang91/nvim-ufo/assets/64155612/a267eb77-e28c-4d8e-b0d2-f8d7a18d5769)

**Comment by kevinhwang91** [comment]
Not a bug for ufo, check out which plugin renders foldcolumn in your plugin list.
