### ISSUE TITLE
Resize Fold Column Width

### ISSUE THREAD

**Issue by andregpss** [kevinhwang91/nvim-ufo#197]
### Feature description

To set up the fold column width. On my NVim configuration, that column is thin so we can almost see the icons. It is the first column, next to the Git column.
![image](https://github.com/kevinhwang91/nvim-ufo/assets/24927386/7ba3cd7d-0b89-4540-bd03-4acb5aaaf790)

### Describe the solution you'd like

A property like:

> nvim.o.foldcolumnwidth=5

**Comment by rockyzhang24** [comment]
The width of each fold column can not be changed. It's a fixed width equal to the char cell width set by the terminal itself. Next, `nvim.o` is for neovim's builtin options and a single plugin cannot add and define more options.
