### ISSUE TITLE
All folds automatically closing if I open the help menu before opening a file

### ISSUE THREAD

**Issue by rnwtn** [kevinhwang91/nvim-ufo#199]
### Neovim version (nvim -v | head -n1)

NVIM v0.9.5

### Operating system/version

Void Linux

### How to reproduce the issue

My UFO setup: https://github.com/rnwtn/nvim-config/blob/master/lua/user/plugins/lsp.lua#L79-L100

Steps to reproduce starting from outside neovim:
1. nvim
2. :h
3. :q
4. :e \<some file that has folds>
    - The folds fold automatically

### Expected behavior

No folds should close automatically when opening a file after opening and closing the help menu.

### Actual behavior

Folds fold automatically if I open the help menu, close it, then open a file.

A video might explain it better: https://streamable.com/dn9l7t
I open neovim and then open a file to show that no folds happen automatically. Then I open neovim and perform the steps to reproduce to show how the folds are folding automatically.

I didn't show this in the video, but this also happens if I open neovim and select a file from fugitive. And it also happens if I open my file tree, close it, then select a file.

**Comment by kevinhwang91** [comment]
can't reproduce.
