### ISSUE TITLE
Question:  Changing or disabling folded line highlighting

### ISSUE THREAD

**Issue by RBoroot** [kevinhwang91/nvim-ufo#217]
### Feature description

Hi!
Pretty new and dont know if this is a good place to post a question so sorry if it's not.

Basically, searching the docs for a way to disable or soften the folded line highlighting and can't find anything. Gets quite messy with multiple folds.

Is it tied to the colorscheme or somewhere else i should be looking? (I noticed the highlight sometimes dissapears with different colorshemes, using catppuccin atm)

![240502_18h12m37s_screenshot](https://github.com/kevinhwang91/nvim-ufo/assets/104057807/51c4bbc4-a1ef-4099-a31a-1e1a75e0e5ec)

Thanks for all the input and help!

### Describe the solution you'd like

Softer folded line highlight. Even removing the highlight and having just the fold arrows on the left would be better...

**Comment by kevinhwang91** [comment]
I can't understand what issue you are having.

**Comment by RBoroot** [comment]
Hi, thanks for the reply!

Im looking for a way to disable or change the color of the folded code highlight bar.

When the code is folded, its indicated by a horizontal bar. When i have many folds in the code it looks so messy and distracting. 

Is there a way to disable it? Just the three dots or the arrows on the left in the status bar would be better. Or at least to soften it so it looks more like the cursor bar...

Maybe its controlled by the colorscheme or something else...

Hope it makes sense and hanks for all the help

**Comment by kevinhwang91** [comment]
https://github.com/kevinhwang91/nvim-ufo?tab=readme-ov-file#customize-fold-text

You should read https://github.com/kevinhwang91/nvim-ufo/blob/a5390706f510d39951dd581f6d2a972741b3fa26/lua/ufo.lua#L162-L191
