### ISSUE TITLE
Nothing displayed at the first line after folded

### ISSUE THREAD

**Issue by nasoundead** [kevinhwang91/nvim-ufo#225]
### Neovim version (nvim -v | head -n1)

NVIM 0.10.0

### Operating system/version

windows10

### How to reproduce the issue

`cat mini.lua`
```lua
-- Use Vim packages install the plugin, also work with some plugins manager such as packer.nvim
vim.o.packpath = '~/.local/share/nvim/site'
vim.cmd('packadd promise-async')
vim.cmd('packadd nvim-ufo')

-- Setting
vim.o.foldcolumn = '1'
vim.o.foldlevel = 99
vim.o.foldlevelstart = -1
vim.o.foldenable = true

local ufo = require('ufo')
ufo.setup()
vim.keymap.set('n', 'zR', ufo.openAllFolds)
vim.keymap.set('n', 'zM', ufo.closeAllFolds)
```
`nvim --clean +'so mini.lua'`

1.
2.
3.
...

### Expected behavior

The first Line should display

### Actual behavior

![image](https://github.com/kevinhwang91/nvim-ufo/assets/13186459/3bfe37be-09bd-4f15-a839-d0b7d5ec277f)
First line of folding is disapeared!
![image](https://github.com/kevinhwang91/nvim-ufo/assets/13186459/f56ad05d-eaca-4e8b-b9de-2d17fb38450f)

**Comment by kevinhwang91** [comment]
check out your `foldtext`

**Comment by nasoundead** [comment]
Could you give more info about foldtext?  My config wrong?

**Comment by kevinhwang91** [comment]
Please use a mini config, `foldtext` is changed to `v:lua.require'ufo.main'.foldtext()`  that is needed by ufo.

**Comment by kevinhwang91** [comment]
No, follow the issue template and provide reproduce steps.

**Comment by nasoundead** [comment]
Sorry, I can not give more info. This is inevitable.

**Comment by nasoundead** [comment]
I give up

**Comment by wllenyj** [comment]
The same problem for me.
