### ISSUE TITLE
neovim crashes on using nvim-ufo

### ISSUE THREAD

**Issue by snr2718** [kevinhwang91/nvim-ufo#228]
### Neovim version (nvim -v | head -n1)

NVIM v0.10.0

### Operating system/version

Arch Linux

### How to reproduce the issue

Dir path
`nvim/username/lazy.lua`
```lazy.lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
     "git",
     "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable",
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)
--require("lazy").setup({import="snr2718.plugins"}, {import="snr2718.plugins.lsp"})
require("lazy").setup({ -- UFO
  "kevinhwang91/nvim-ufo",
   dependencies = "kevinhwang91/promise-async",
   event = "VimEnter", -- needed for folds to load in time and comments closed
   config = function()
     require('ufo').setup()
    end,
})
```

Dir path
`nvim / init.lua`
```init.lua
require("username/lazy.lua")
```

Steps to reproduce

1. open "nvim/username/lazy.lua"
2. Give enough time and it will automatically crash. If not, keep pressing "j" to go down the lines and nvim will crash and exit.

Note: Opening "nvim/init.lua" doesn't crash `nvim`. Maybe because there are no folds ? Not sure.
...

### Expected behavior

Nvim shouldn't crash

### Actual behavior

Nvim crashes

**Comment by kevinhwang91** [comment]
Not a lazy user.

**Comment by xuanhung1509** [comment]
I got the same problem on v0.10.0. Neovim starts as normal, but will silently quit after 3-5s afterwards. I try to lazy load `ufo` on `LspAttach` or at startup, but no luck.

**Comment by xuanhung1509** [comment]
> I got the same problem on v0.10.0. Neovim starts as normal, but will silently quit after 3-5s afterwards. I try to lazy load `ufo` on `LspAttach` or at startup, but no luck.

Never mind. I update to latest version and it works now.
