### ISSUE TITLE
Error on clangd.

### ISSUE THREAD

**Issue by aabbccddeeffggj** [kevinhwang91/nvim-ufo#229]
### Neovim version (nvim -v | head -n1)

0.10.0

### Operating system/version

Linux 6.9.6

### How to reproduce the issue

```lua
-- Use Vim packages install the plugin, also work with some plugins manager such as packer.nvim
vim.o.packpath = '~/.local/share/nvim/site'
vim.cmd('packadd promise-async')
vim.cmd('packadd nvim-ufo')

-- Setting
vim.o.foldcolumn = '1'
vim.o.foldlevel = 99
vim.o.foldlevelstart = -1
vim.o.foldenable = true

local ufo = require('ufo')
ufo.setup()
vim.keymap.set('n', 'zR', ufo.openAllFolds)
vim.keymap.set('n', 'zM', ufo.closeAllFolds)
```

1. Have clangd functioning.
2. Set the following attached to the language server:
```lua
local fold = vim.lsp.protocol.make_client_capabilities()
fold.textDocument.foldingRange = {
  dynamicRegistration = false,
  lineFoldingOnly = true
}
lsp.clangd.setup {
  capabilities = fold
}

```
3. Have anything in your clipboard
4. Open a *.cpp file
5. Have anything written in it.
6. select all lines with Shift+v
7. Press p

### Expected behavior

Not to display `Error executing vim.schedule lua callback: UnhandledPromiseRejection with the reason:
RPC[Error] code_name = InvalidParams, message = "trying to compute folding ranges for non-added document"` and not stop the plugin's folding to work.

### Actual behavior

Displays `Error executing vim.schedule lua callback: UnhandledPromiseRejection with the reason:
RPC[Error] code_name = InvalidParams, message = "trying to compute folding ranges for non-added document"` and the plugin's folding stops working.

**Comment by kevinhwang91** [comment]
can't reproduce it. 
clangd version: ?
issue repository: ?

**Comment by aabbccddeeffggj** [comment]
> clangd version

18.1.3 (the last version till now)

> issue repository

I'm on the last commit of the repository (aa2e676)

I made this minimal working example (it automatically downloads the last version of clangd and sets up the language server to automatically work out-of-the-box):
```lua
--Enable global clipboard
vim.opt.clipboard:append("unnamedplus")

--Plugin manager
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable",
    lazypath
  })
end
vim.opt.rtp:prepend(lazypath)

--Plugins
require("lazy").setup({
  'neovim/nvim-lspconfig',
  'williamboman/mason.nvim',
  'williamboman/mason-lspconfig.nvim',
  'kevinhwang91/nvim-ufo',
  'kevinhwang91/promise-async'
})

--LSP provider
require('mason').setup()

--Automaticaly download clangd
require('mason-lspconfig').setup {ensure_installed = {'clangd'}}

--Automatically start lsp on C/C++ files
require('lspconfig').clangd.setup {
  capabilities = fold
}

--Folding
require('ufo').setup()
local fold = vim.lsp.protocol.make_client_capabilities()
fold.textDocument.foldingRange = {
  dynamicRegistration = false,
  lineFoldingOnly = true
}
```

**Comment by kevinhwang91** [comment]
Sorry, I mean the issue file of the codebase.

**Comment by aabbccddeeffggj** [comment]
I'm not sure if I understand what this would be.

**Comment by kevinhwang91** [comment]
.cpp project

**Comment by aabbccddeeffggj** [comment]
I see, it's a single file, there could be any text inside it, but as an example:
```cpp
#include <iostream>

int main() {
  int x{};
  std::cout << "x is " << x << '\n';
  return 0;
}
```
1. Have anything copied in the clipboard.
2. Press "shift+v" and select all lines of this file (from the top to the bottom of the file).
3. Press "p" while you have these lines selected (to paste whatever you have in your clipboard).

**Comment by kevinhwang91** [comment]
Even disable ufo, the error msg `trying to get AST for non-added document` output from the `lsp.log`. It Looks like the text document is out of sync with the server. The buffer can't do anything lsp actions.
