### ISSUE TITLE
Is it possible to add folds for the sections and the subsections of rmarkdown/quarto documents?

### ISSUE THREAD

**Issue by onurcanbektas** [kevinhwang91/nvim-ufo#231]
### Feature description

In the current version of the package, markdown sections are not folded by default. Is it possible to fold sections/subsections in Rmarkdown/quarto files as well?

### Describe the solution you'd like

Org-mode like folding where one can get an overview of all sections by closing all folds

**Comment by kevinhwang91** [comment]
Have you tried `treesitter` provider?

**Comment by onurcanbektas** [comment]
@kevinhwang91  yes, it doesn't really work on rmarkdown/quarto documents.

**Comment by kevinhwang91** [comment]
Look like the rmd file type is missing `lsp` or `treesitter` provider. ufo can't parse any fold ranges about syntax token.
