### ISSUE TITLE
zC function

### ISSUE THREAD

**Issue by HeraPtt** [kevinhwang91/nvim-ufo#232]
### Feature description

Is there anyway to fold under cursor recursively?

### Describe the solution you'd like

like zC not zM

**Comment by kevinhwang91** [comment]
What's the issue for built-in `zC`?

**Comment by HeraPtt** [comment]
> What's the issue for built-in `zC`?

it folds every thing not what my cursor is on like zM

**Comment by kevinhwang91** [comment]
Your remap `zC` issue.
