### ISSUE TITLE
attemp to call field 'nvim__redraw'

### ISSUE THREAD

**Issue by lee-shun** [kevinhwang91/nvim-ufo#234]
### Neovim version (nvim -v | head -n1)

NVIM v0.10.0-dev

### Operating system/version

ubuntu20.04

### How to reproduce the issue

1. use the following config with lazy;
```lua
return {
    "kevinhwang91/nvim-hlslens",
    event = "VeryLazy",
    enabled = false,
    keys = {
        { "n",  [[<cmd>execute('normal! ' . v:count1 . 'n')<cr><cmd>lua require('hlslens').start()<cr>]] },
        { "N",  [[<cmd>execute('normal! ' . v:count1 . 'N')<cr><cmd>lua require('hlslens').start()<cr>]] },
        { "*",  [[*<cmd>lua require('hlslens').start()<cr>]] },
        { "#",  [[#<cmd>lua require('hlslens').start()<cr>]] },
        { "g*", [[g*<cmd>lua require('hlslens').start()<cr>]] },
        { "g#", [[g#<cmd>lua require('hlslens').start()<cr>]] },
    },
    config = true,
}

```
2. open the nvim with a file
the error is:
![image](https://github.com/user-attachments/assets/664e265c-c772-4d1a-a0ed-c6b9072b0207)

### Expected behavior

no errors

### Actual behavior

the above-mentioned error occurs when opening the file.

**Comment by lee-shun** [comment]
@kevinhwang91

**Comment by kevinhwang91** [comment]
Only this error appeared for the first open?

**Comment by renauga** [comment]
I am experiencing this issue too. As of now, I've seen it appear when entering buffers.

**Comment by kevinhwang91** [comment]
What's the `lua =vim.api.nvim__redraw` output? Is the result is `<function 1>` ? Look like the lazy issue.

**Comment by simonlearnscoding** [comment]
experiencing the same issue since an update

**Comment by TioeAre** [comment]
I encountered a similar problem. But with the same config, the problem only occurred on the remote server when i open a file, and no error was reported in nvim on my local machine.

outputs are as follows

```bash
Error in decoration provider ufo.end:
Error executing lua: ...24/.local/share/nvim/lazy/nvim-ufo/lua/ufo/decorator.lua:132: attempt to call field 'nvim__redraw' (a nil value)
stack traceback:
    [C]: in function 'error'
    ...24/.local/share/nvim/lazy/nvim-ufo/lua/ufo/decorator.lua:143: in function <...24/.local/share/nvim/lazy/nvim-ufo/lua/ufo/decorator.lua:140>
    [C]: in function 'nvim_command'
    ....local/share/nvim/lazy/nui.nvim/lua/nui/popup/border.lua:624: in function '_relayout'
    ...4/.local/share/nvim/lazy/nui.nvim/lua/nui/popup/init.lua:390: in function 'update_layout'
    ...4/.local/share/nvim/lazy/nui.nvim/lua/nui/popup/init.lua:158: in function 'init'
    .../.local/share/nvim/lazy/nui.nvim/lua/nui/object/init.lua:132: in function <.../.local/share/nvim/lazy/nui.nvim/lua/nui/object/init.lua:130>
    ....local/share/nvim/lazy/noice.nvim/lua/noice/view/nui.lua:92: in function 'create'
    ....local/share/nvim/lazy/noice.nvim/lua/noice/view/nui.lua:271: in function 'show'
    ...local/share/nvim/lazy/noice.nvim/lua/noic
Error in decoration provider ufo.end:
Error executing lua: ...24/.local/share/nvim/lazy/nvim-ufo/lua/ufo/decorator.lua:132: attempt to call field 'nvim__redraw' (a nil value)
stack traceback:
    [C]: in function 'error'
    ...24/.local/share/nvim/lazy/nvim-ufo/lua/ufo/decorator.lua:143: in function <...24/.local/share/nvim/lazy/nvim-ufo/lua/ufo/decorator.lua:140>
```

**Comment by kevinhwang91** [comment]
Only this error appeared for the first open?

**Comment by TioeAre** [comment]
> Only this error appeared for the first open?

It seems to happen when read a new buffer or toggle a fold. And `:lua =vim.api.nvim__redraw` outputs `nil`

**Comment by kevinhwang91** [comment]
> > Only this error appeared for the first open?
> 
> It seems to happen when read a new buffer or toggle a fold. And `:lua =vim.api.nvim__redraw` outputs `nil`

I guess it is lazy issue. `nlua_init` -> `nlua_state_init` -> `nlua_add_api_functions`.  `vim.api.nvim__redraw` never become `nil` after nvim initialized except other plugins make it to be `nil`.
https://github.com/neovim/neovim/blob/aa853f362addded400d52d8fdfe5247c300c0e89/build/src/nvim/auto/lua_api_c_bindings.generated.h#L8981-L8982

**Comment by TioeAre** [comment]
I tried the latest [nvim v0.10.1](https://github.com/neovim/neovim/releases/tag/v0.10.1) just now, and the error seems disappeared.

Before that, my nvim version is `NVIM v0.10.0-dev-2999+g38b9c322c`.

Thank you very much for your reply!
