### ISSUE TITLE
nvim-ufo interferes with cursorline mapping

### ISSUE THREAD

**Issue by sainttttt** [kevinhwang91/nvim-ufo#242]
### Neovim version (nvim -v | head -n1)

NVIM v.0.10.0

### Operating system/version

macOS 13.6.1

### How to reproduce the issue

I have an autocommand for my CursorLine that gets it to flash when I yank text, and also changes when I enter insert mode. nvim-ufo overrides these settings.

If I remove this code
```
-            if curLnum == curFoldStart then
-                didHighlight = wses:setCursorFoldedLineHighlight()
-            else
-                didHighlight = wses:clearCursorFoldedLineHighlight()
-            end
```
from `lua/ufo/decorator.lua` then it seems to work fine.

These are my autocommands:
```
augroup yank_text_highlight
  autocmd!
  autocmd InsertEnter * highlight CursorLine guibg=#181010
  autocmd InsertLeave * hi! link CursorLine CursorLineMain
  autocmd TextYankPost * hi! link CursorLine YankText | call timer_start(200, { tid -> execute('hi! link CursorLine CursorLineMain')})
augroup END
```

Could the functionality of nvim-ufo setting CursorLine be turned off via some option?

### Expected behavior

CursorLine mappings remain unaltered

### Actual behavior

Cursorline autocommands get overwritten and stop working when I use nvim-ufo

**Comment by kevinhwang91** [comment]
I can't understand what the issue is. ufo never change

**Comment by sainttttt** [comment]
So I'm still having the issue - it might be a bug with nvim though. I've linked a video showcasing the issue here:

https://streamable.com/4t7lki

So I have an autocommand that does a link from CursorLine to CursorLineEdit on InsertEnter. I'm also echoing "linking" everytime this autocommand runs. After nvim-ufo does it's link of CursorLine to UfoCursorFoldedLine, this some how breaks the autocommand functionality. The autocommand still runs but the highlight doesn't get updated. 

However if I move the cursor from the buffer to another buffer and back then it startrs working again. Any idea how to fix this? Would it be possible at all to add an option to simply turn off the UfoCursorFoldedLine highlighting? I don't currently use that and if it's turned off then I don't have any issues.

Thanks!

**Comment by kevinhwang91** [comment]
Update the code, it should work now.

**Comment by sainttttt** [comment]
Working now, thanks!
