### ISSUE TITLE
VsCode like foldlevel

### ISSUE THREAD

**Issue by tibimunteanu** [kevinhwang91/nvim-ufo#244]
### Feature description

VsCode has these commands to fold specific levels. If you call foldlevel 1, it folds ONLY level 1.
Can we achieve that with ufo?

### Describe the solution you'd like

Provide foldlevel commands that only fold specific levels, NOT all levels greater than the specified one

**Comment by kevinhwang91** [comment]
`vim.keymap.set('n', 'zm', require('ufo').closeFoldsWith) `
https://github.com/kevinhwang91/nvim-ufo/blob/7dcb8fea3e7b3ccdb50f2c3ae7c248cdf6fe1ae1/lua/ufo.lua#L40-L45

type `count zm` will make what you want.

**Comment by tibimunteanu** [comment]
not really.
if I do `1zm` it will fold level 1, 2, 3, 4, ... 99
yes.. I can then use `zA` to unfold all levels at the cursor, but I prefer to just do `za` to toggle. but `za` will only open level 1 and leave levels 2, 3, 4, ... 99 open.
In VsCode, the foldlevel 1 command would just fold that level.

**Comment by tibimunteanu** [comment]
I can just use `zA` to toggle all levels at the cursor and it seems similar to what I need. Thank you!
