### ISSUE TITLE
UnhandledPromiseRejection error on saving

### ISSUE THREAD

**Issue by yriveiro** [kevinhwang91/nvim-ufo#246]
### Neovim version (nvim -v | head -n1)

NVIM v0.11.0-dev-3809+g91ce0c3dd-Homebrew

### Operating system/version

macOS 14.6.1

### How to reproduce the issue

1. Open a Golang project
2. Save the file
3. The error happen

### Expected behavior

No error on saving the file.

### Actual behavior

The error is triggered when I save the file.

```sh
 Error  12:27:21 msg_show.lua_error Error executing vim.schedule lua callback: UnhandledPromiseRejection with the reason:
     4 vim/shared.lua:0: t: expected table, got nil
     5 stack traceback:
     6 > [C]: in function 'error'
     7 > vim/shared.lua: in function 'validate'
     8 > vim/shared.lua: in function 'tbl_contains'
     9 > ....local/share/nvim/lazy/nvim-ufo/lua/ufo/fold/manager.lua:174: in function 'applyFoldRanges'
    10 > ...ro/.local/share/nvim/lazy/nvim-ufo/lua/ufo/fold/init.lua:97: in function <...ro/.local/share/nvim/lazy/nvim-ufo/lua/ufo/fold/init.lua:87>
```

**Comment by kevinhwang91** [comment]
Your `close_fold_kinds_for_ft` config issue.

**Comment by yriveiro** [comment]
Hi,

Indeed, it was a configuration problem, that was my config.

﻿```lua
﻿      local kinds = { 'imports', 'comment' }

      require('ufo').setup {
        ...
        close_fold_kinds_for_ft = kinds
        ...
      }
```
It seems that the correct way to put kind is like this following this [code](https://github.com/kevinhwang91/nvim-ufo/blob/b23a46aa06f5f653d107efbc67fd2aa3877ac344/lua/ufo.lua#L55)

```lua
close_fold_kinds_for_ft = { default = { 'imports', 'comment' } }
```
or in the case, we want more control by ft

```lua
close_fold_kinds_for_ft = { lua = { 'imports', 'comment' } }
```

Thank you for the help. I was confused about how to set up this property, but it is clear now. And thank you for this plugin 😃
