### ISSUE TITLE
Question: what is this numbers in the sign column?

### ISSUE THREAD

**Issue by augustocdias** [kevinhwang91/nvim-ufo#248]
What is these numbers in the sign column and how do I disable them?

![image](https://github.com/user-attachments/assets/86a1bb2e-1f27-41cc-a4f7-920efc83ae01)

Another question: I'm using the lsp provider and it takes a long time after the lsp is initialized for the folds to appear. Sometimes I have to call `LspInfo` for it to force the folds to render. Is that normal? I have just the minimal config from the README.

**Comment by kevinhwang91** [comment]
https://github.com/kevinhwang91/nvim-ufo/issues/4

**Comment by augustocdias** [comment]
> #4

Thanks. so there's no way without building neovim from source? is there an issue on neovim to add an option for that?

**Comment by kevinhwang91** [comment]
> > #4
> 
> Thanks. so there's no way without building neovim from source? is there an issue on neovim to add an option for that?

Have you seen https://github.com/kevinhwang91/nvim-ufo/issues/4#issuecomment-1500925173?

**Comment by augustocdias** [comment]
statuscol didn't really worked... I'll ask on that repo then...

Thanks
