### ISSUE TITLE
Automatic folds

### ISSUE THREAD

**Issue by Mte90** [kevinhwang91/nvim-ufo#25]
### Feature description

There is https://github.com/Konfekt/FastFold  maybe this plugin can integrate the feature itself so we can remove another viml dependence.

### Describe the solution you'd like

Auto fold documentation code.

**Comment by kevinhwang91** [comment]
I can't get your point. I guess you misunderstand how ufo works.

**Comment by kevinhwang91** [comment]
Yes, but Why do you need `FastFold`?
What's use case can't `lsp`, `indent` and `treesitter` providers cover with? ufo respect provider interface.

**Comment by Mte90** [comment]
Perfect, clear :-)
