### ISSUE TITLE
My opened folds close after saving buffer

### ISSUE THREAD

**Issue by dinno7** [kevinhwang91/nvim-ufo#250]
### Neovim version (nvim -v | head -n1)

NVIM v0.10.1

### Operating system/version

Arch linux

### Expected behavior

I want all my folds close by default when i open a new buffer, when i set foldlevel = 0, it is close all buffers after opening a new buffer but the problem is when i save the file, my opened folds close again and i do not want this.

### Actual behavior

I want all my folds close by default **just** when i open the file, i do not want to close my opened folds after saving the file!

**Comment by dinno7** [comment]
> `foldlevelstart = 0`

it is not work, every fold will be close in opening a buffer correctly
But when I open some folds and save the file(:w), all my opened folds close again and I do not want this
I want all folds close by default **JUST** when I enter the buffer not anytime I save it.

My options is as below:

o.foldcolumn = "auto:9"
o.foldlevel = 99
o.foldlevelstart = 0
o.foldenable = true

**Comment by kevinhwang91** [comment]
https://github.com/kevinhwang91/nvim-ufo/issues/146

**Comment by dinno7** [comment]
Thanks
