### ISSUE TITLE
No folding except for manual

### ISSUE THREAD

**Issue by jwbullard** [kevinhwang91/nvim-ufo#253]
### Neovim version (nvim -v | head -n1)

NVIM v0.10.2

### Operating system/version

macOS 14.7

### How to reproduce the issue

1. Install nvim-ufo via lazy.nvim with this lua file
```
return {
  "kevinhwang91/nvim-ufo",
  dependencies = "kevinhwang91/promise-async",
  config = function()
    vim.o.foldmethod = "indent"
    vim.o.foldcolumn = "1" -- '0' is not bad
    vim.o.foldlevel = 99 -- Using ufo provider needs a large value
    vim.o.foldlevelstart = 99
    vim.o.foldenable = true

    vim.keymap.set("n", "zO", require("ufo").openAllFolds, { desc = "Open all folds" })
    vim.keymap.set("n", "zC", require("ufo").closeAllFolds, { desc = "Close all folds" })
    vim.keymap.set("n", "zK", function()
      local winid = require("ufo").peekFoldedLinesUnderCursor()
      if not winid then
        vim.lsp.buf.hover()
      end
    end, { desc = "Peek Fold" })

    require("ufo").setup({
      provider_selector = function(bufnr, filetype, buftype)
        return { "lsp", "indent" }
      end,
    })
  end,
}
```
2. Open any C source code file.
3. No folding is shown
4. Use command `:set foldmethod` to ensure that the method is set to `indent`
5. Still no folding shown at any level

### Expected behavior

With the foldmethod set to indent, when I open this C file:
```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(void) {
  int i = 0;
  int j = 1;
  return 0;
}
```
I expect to see everything within the main function folded.

If I issue the command `:checkhealth` I expect to see an entry for nvim-ufo.

### Actual behavior

When I open this C file, there is no code folding at all.
```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(void) {
  int i = 0;
  int j = 1;
  return 0;
}
```
With this file still open, I checked with `:set foldmethod` and it is set to `indent`.
I checked shiftwidth `:set shiftwidth` and it is set to 2. I checked foldminlines with `:set foldminlines` and it is set to 1.  Finally, I checked foldlevel with `:set foldlevel` and it is set to 99.

When I issue the command `:checkhealth` the nvim-ufo does not show up at all.

**Comment by jwbullard** [comment]
Also I just checked in `~/.local/share/nvim/lazy` and there *is* a folder for nvim-ufo, so I assume it is being installed.

**Comment by kevinhwang91** [comment]
Don't lazy load ufo with lazy.

**Comment by jwbullard** [comment]
I set lazy to false inside nvim-ufo.lua, and it still doesn't work.  Is this what you meant?
```
return {
  "kevinhwang91/nvim-ufo",
  lazy = false,
  dependencies = "kevinhwang91/promise-async",
  config = function()
    vim.o.foldmethod = "indent"
    vim.o.foldcolumn = "1" -- '0' is not bad
    vim.o.foldlevel = 99 -- Using ufo provider needs a large value
    vim.o.foldlevelstart = 99
    vim.o.foldenable = true

    vim.keymap.set("n", "zO", require("ufo").openAllFolds, { desc = "Open all folds" })
    vim.keymap.set("n", "zC", require("ufo").closeAllFolds, { desc = "Close all folds" })
    vim.keymap.set("n", "zK", function()
      local winid = require("ufo").peekFoldedLinesUnderCursor()
      if not winid then
        vim.lsp.buf.hover()
      end
    end, { desc = "Peek Fold" })

    require("ufo").setup({
      provider_selector = function(bufnr, filetype, buftype)
        return { "lsp", "indent" }
      end,
    })
  end,
}
```

**Comment by kevinhwang91** [comment]
vim.o.foldmethod = "manual"

**Comment by jwbullard** [comment]
Sorry, that had no effect whatsoever.  Here is my new nvim-ufo.lua:
```
return {
  "kevinhwang91/nvim-ufo",
  lazy = false,
  dependencies = "kevinhwang91/promise-async",
  config = function()
    vim.o.foldmethod = "manual"
    vim.o.foldcolumn = "1" -- '0' is not bad
    vim.o.foldlevel = 99 -- Using ufo provider needs a large value
    vim.o.foldlevelstart = 99
    vim.o.foldenable = true

    vim.keymap.set("n", "zO", require("ufo").openAllFolds, { desc = "Open all folds" })
    vim.keymap.set("n", "zC", require("ufo").closeAllFolds, { desc = "Close all folds" })
    vim.keymap.set("n", "zK", function()
      local winid = require("ufo").peekFoldedLinesUnderCursor()
      if not winid then
        vim.lsp.buf.hover()
      end
    end, { desc = "Peek Fold" })

    require("ufo").setup({
      provider_selector = function(bufnr, filetype, buftype)
        return { "lsp", "indent" }
      end,
    })
  end,
}
```
Also, when I run :checkhealth there is nothing showing for nvim-ufo.  No entries, no errors, nothing.  However, the nvim-ufo keymaps *do* work, like zC for closing all folds.

The main issue seems to be that setting the foldmethod to indent does nothing at all.  Maybe that is not a problem with nvim-ufo but with nvim cold folding in general, but I'm not sure how to check that.

**Comment by kevinhwang91** [comment]
Run `UfoInspect` command to check out whether the buffer is attached by ufo.

**Comment by jwbullard** [comment]
Thank you. Here is the output:
```
Buffer: 1
Fold Status: start
Main provider: lsp
Fallback provider: indent
Selected provider: lsp
Fold kinds: region
```

**Comment by kevinhwang91** [comment]
ufo only apply fold if the foldmethod is `manual`, some scripts change its value.

**Comment by jwbullard** [comment]
I see.  As a test, I uninstalled nvim-ufo from my setup and the indent method now works perfectly.  I suppose I need to learn more about how nvim-ufo is supposed to work.  I will study it more.  Thank you for your help.
