### ISSUE TITLE
Include the bottom line inside a fold

### ISSUE THREAD

**Issue by akinsho** [kevinhwang91/nvim-ufo#26]
### Feature description

In editors like intellij or simply using a custom fold text in vim, it is possible to include the bottom like as part of a fold like in the screenshot below

![image](https://user-images.githubusercontent.com/22454918/175942781-b209dcaf-d62f-48f1-9b83-d8d00a2e3745.png)

Note that the trailing `}` is displayed as part of the `{...}` on the folded line rather than below it on a new line.

### Describe the solution you'd like

As described above it would be nice if a user could include the closing item e.g. the closing parentheses as part of a fold rather than trailing outside of it e.g.

```js
// Desired outcome
function testThing() {...} // The closing parens are on the same line as the fold.

// Current state
function testThing() { ...
}
```

This would also allow something like
```js
import {...} from "thing"
```

by using whatever the trailing content of the last fold line is appended to the fold text

**Comment by kevinhwang91** [comment]
Depend on your folding range provider, but I found most of them can't support this feature for now.
However, ufo use two interfaces to imp it, but must handle the function yourself.
```lua
-- Run me.
local async = require('async')
local promise = require('promise')
require('ufo').setup({
    provider_selector = function(bufnr, filetype)
        if filetype == 'javascript' then
            return function()
                return async(function()
                    local data = await(promise.all({
                        folds = require('ufo').getFolds('lsp', bufnr),
                        symbols = promise(function(resolve, reject)
                            -- request `textDocument/documentSymbol` to get the context you want
                            resolve('expected data')
                        end)
                    }))

                    local function handle()
                        -- handle the folds
                        -- and export the context
                        _G.ufo_context = ''
                        return data.folds
                    end

                    return handle()
                end)
            end
        end
    end,
    fold_virt_text_handler = function(virtText, lnum, endLnum, width, truncate)
        -- make your new virtText append `}` with `ufo_context`
        return virtText
    end
})
```

`import {...} from "thing"` 

1. If the modules are multiple lines, ufo can imp it like the above code snippet I post.
2.  If the modules are all in single la ine, ufo can't redrew the virtual text. For now, only work with `foldminlines` > 0.

Perf will regress if `foldminlines` == 0, need time to export how many.

**Comment by akinsho** [comment]
@kevinhwang91 not entirely sure if I understand exactly what this solution means really but a few things to note are that I don't really want this to be a per language thing I think (at least in my head) the idea would be that since presumably the fold is an `expr` there could be a general solution to just extend the range of the fold from the LSP provider by 1 *as an option*, so it always captures the last line. This way users who want this don't have to re-implement providers themselves just to extend the range, I don't really know how straightforward or not this is really tbh I just assumed that the mechanism used involved telling nvim where the start and end of a fold was so that it would just be a matter of adding one.

Then all that would be needed would be to append the contents of `endLnum` to the virtual text.

Tbh the `import` example was just an example so not the end of the world if that can't work

**Comment by kevinhwang91** [comment]
This feature is IDE-like feature and must customize for a certain language because LSP doesn't support it.
I can't find an easy way to imp this feature because lacking support from LSP, and VSCode also doesn't support it officially.

We must solve the issue of foldingranges source first and then consider the virtual text.

**Comment by kevinhwang91** [comment]
ufo request folding range from providers (language server or native provide like `indent`), return https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#foldingRange and apply them by `s,efold` command (but using FFI is a bit diff)

If you don't care about the perf, you can you use multiple providers to hack (`lsp` and `treesitter`). AFAIK, using symbols and fold ranges from the language server will get the best perf. You also can use a middleware to enhance fold range to support it directly from the language server-side.

**Comment by kevinhwang91** [comment]
> Can you explain a bit more how this would work? Is there an vim.lsp.handers['foldingMethod'] to override or something so that I can change the value that is returned by the LSP so that it is adjusted to behave as I've described?

Unformatually, nvim core with a  folding range handler for now, ufo implement itself. You can use `require('ufo').getFolds('lsp', bufnr)` get the folding, return value is `promise` wrapping foldings.

**Comment by akinsho** [comment]
I just tried this out locally, and it doesn't quite work, unfortunately. Just adding one to all the end lines of each fold and then trying to append the adjusted last line doesn't work since for example

```lua
local t = {
  field = { -- the fold end here comes back as "nested = {"
	nested = {
		value = 1
    },
  }
}
```

The end line is sometimes incorrect. There needs to be a smarter mechanism to determine the end rather than a brute force + 1. I guess this comes back to what you said about how the lsp handles this. 

I guess one way could be when processing the folds you could fetch the lines in the buffer once and check the `endLine + 1` and if it matches like closing characters e.g. `/^(\]\)\})/` then it gets advanced by one otherwise it should be left alone.

Not sure if you could get a robust solution for languages with parens and braces, but maybe a lot of brittle code to take on. I think with a treesitter provider though you could get this behaviour easily since this is already how nvim-treesitter's fold mechanism already works

**Comment by akinsho** [comment]
Found some issues relating to this for [vscode](https://github.com/microsoft/vscode/issues/3352) and [the LSP](https://github.com/microsoft/language-server-protocol/issues/1426). As a side note, it seems that the `collapsedText` field was added to allow custom fold text from the language server so might be cool to support, not that I know/use any that do that.

**Comment by kevinhwang91** [comment]
> The end line is sometimes incorrect. There needs to be a smarter mechanism to determine the end rather than a brute force + 1. I guess this comes back to what you said about how the lsp handles this.

Yes, need AST context, like symbols.  Intellij doesn't handle  `if`, `else`, and `else if ` blocks.

> I think with a treesitter provider though you could get this behaviour easily since this is already how nvim-treesitter's fold mechanism already works

You can wait for the `treesitter` provider this weekend if you like the folding of treesitter. I don't like treesitter folding because it can't fold `if`, `else`, and `else if ` blocks totally.

> Found some issues relating to this for https://github.com/microsoft/vscode/issues/3352 and https://github.com/microsoft/language-server-protocol/issues/1426. As a side note, it seems that the collapsedText field was added to allow custom fold text from the language server so might be cool to support, not that I know/use any that do that.

Folding in Neovim is a line range, not a char range, need hack. IMO, hard to imp as a plugin, but can hack by the person who needs it.

**Comment by akinsho** [comment]
> You can wait for the treesitter provider this weekend if you like the folding of treesitter

That sounds great 🚀 

> I don't like treesitter folding because it can't fold if, else, and else if blocks totally.

Tbh I'd much rather trade the behaviour of folding completely even if it meant not having `if/else` clauses, but AFAIK treesitter can fold these as long as the `folds.scm` has those nodes correctly identified and contributed in upstream `nvim-treesitter`.

Re. the collapsed text was only mentioning in case you hadn't seen it, I didn't realize it only worked with character range folds, in which case fair enough to leave it

**Comment by kevinhwang91** [comment]
The `treesitter` provider has done, after using `treesitter` provider I know why you raise this issue now.

Even using `treesitter` provider, ufo can't do it perfectly, for example

```c
void test()
{
    printf("test");
}
```
vs
```c
void test() {
    printf("test");
}
```
vs
```c
void test() { // how to handle this comment?
    printf("test");
}
```
Fortunately, users can hack what behave they want in `fold_virt_text_handler`, I think getting the  context is simple enough if using treesitter.

**Comment by akinsho** [comment]
@kevinhwang91 not sure how the folds are being handled i.e. via `nvim-treesitter` fold queries or not, but I think the specific language edge cases can be handled in each language's `folds.scm` i.e. in the first example if this was c or something then I imagine that the fold range would be defined as being lines 2-4 e.g.
```c
void test()
{...}
```

Regarding the comment I think when generating the fold text by default it should be everything up till the opening parens and then ellipsis closing paren, it's not reasonable to expect to see the comment IMO and if the user wants that then they can do that themselves I don't think an IDE would show that

**Comment by kevinhwang91** [comment]
@akinsho  Good jobs.

> do you think this could be provided as an option for treesitter only or at least maybe there can be a simpler way to override or tweak the suffix of the virt text that doesn't require a user writing around 30 lines of boilerplate. Maybe something like

For now, I'm not sure.

**Comment by ranjithshegde** [comment]
@akinsho I dug into the source code a bit more and made a slightly more decorative end_lines config.
Please check this [gist](https://gist.github.com/ranjithshegde/5a0ef13cd8c4e547f9085b08a15dad45) if you are interested

**Comment by akinsho** [comment]
@ranjithshegde that's really cool 🚀 although looking at the implementation I'm more convinced that this is best done as something configurable in the plugin since this solution really requires understanding the internals of the plugin to get this result.

You have to mess with its namespace and set your own extmarks which is fine for anyone who is confident doing that but will mean anyone else interested in this functionality will be stuck copy pasting code they likely won't understand. Also, if the internal implementation changes which this solution (which is optimal) depends on, then a user's config will also break and for the inexperienced quite confusingly.

**Comment by ranjithshegde** [comment]
@kevinhwang91 I made the config/gist after yesterday's commit `98b07fc` and it works fine for me.
Tried it with even unique treesitter parsers like `latex`, `supercollider` and `orgmode`. No problems so far.

So, putting this as an advanced example seems good.

As to getting it into codebase as in any form, I do agree that this is a rather opinionated example, and unless people are tinkering with fold methods by changing `foldtext` or writing their own methods, etc (which would make them sort of advanced users) I think most people would just accept and use the defaults.
So for these advanced users, just using the gist or creating their own more efficient versions is fine

**Comment by kevinhwang91** [comment]
> @kevinhwang91 I made the config/gist after yesterday's commit `98b07fc` and it works fine for me. Tried it with even unique treesitter parsers like `latex`, `supercollider` and `orgmode`. No problems so far.
> 
> So, putting this as an advanced example seems good.
> 
> As to getting it into codebase as in any form, I do agree that this is a rather opinionated example, and unless people are tinkering with fold methods by changing `foldtext` or writing their own methods, etc (which would make them sort of advanced users) I think most people would just accept and use the defaults. So for these advanced users, just using the gist or creating their own more efficient versions is fine

Open a feature request, please.

**Comment by akinsho** [comment]
> The issue here is hard to handle the end line perfectly even in VSCode. As a maintainer, I can reduce the obstacles for users , but don't want to maintain the feature with unsolved issues, this is my requirement for my plugin.

So I think this might be the point that is getting a little confused. For *treesitter* this is a solved problem. In order to get it to work for all providers e.g. LSP which is what I think you are referring to, I think this will require changes in dozens of LSP since presumably they all implement this differently. I personally don't think the LSP servers are likely to all adopt this behaviour, but since treesitter is largely agnostic to that sort of issue, I think it's a good way to get this functionality for anyone who wants it. I don't think it's practical to get exactly the same type of folding behaviour from multiple sources, so if this request is not feasible for LSP I think that's fine since it's possible with treesitter

I think this is why offering this as an option *if a user is using treesitter* is good and fairly uncomplicated since out of the box treesitter can do this for most languages I guess. As to this being an opinionated setting, I think the point is that it's a "popular" opinion but regardless of this it would be gated by an option and not default 🤷🏿‍♂️ 

Anyway, for fear of making this all too confusing, either of these options is perfectly fine
1. A gist to use that doesn't depend too heavily on internals, i.e. things like namespace are exposed to the user, and they don't have to require modules that are not maybe intended for public use/breakable
2. An option to do auto this automatically and *only when set to true and only for treesitter*

**Comment by ranjithshegde** [comment]
> 1. A gist to use that doesn't depend too heavily on internals, i.e. things like namespace are exposed to the user, and they don't have to require modules that are not maybe intended for public use/breakable
> 2. An option to do auto this automatically and _only when set to true and only for treesitter_

@akinsho 
1. Great point! my example uses internals that was perhaps never meant for the user to tinker with
2.  For this point the below example does do the job, but keep in mind that this is my hack, after having inspected only the relevant parts of the codebase, I have not studied the whole project, so probably it is too hacky
```lua
-- In lua/ufo/decorator.lua -- function onEnd(name, tick), line 110
if someProviderGetApi == "treesitter" and userDefinedCoing.enable_fold_end_virt_text then
  local end_text = api.nvim_buf_get_lines(bufnr, endLnum - 1, endLnum, false)[1]
  local end_virtText = render.getVirtText(bufnr, end_text, width, endLnum, syntax, nss)

  for _, v in ipairs(end_virtText) do
      table.insert(virtText, v)
  end
end
```

**Comment by kevinhwang91** [comment]
Add `enable_fold_end_virt_text` is not bad.

**Comment by ranjithshegde** [comment]
Thanks for the PR! works like a charm!

**Comment by akinsho** [comment]
Going to close this out since I think there's a good enough solution that solves the issue I had

**Comment by akinsho** [comment]
@kevinhwang91 not a bug and also not related to this issue just not sure how else to get this information to you, you might already know don't know if you are on the neovim matrix or watching PRs but https://github.com/neovim/neovim/issues/19226 is in progress which might be interesting for you (just a random FYI not specific motivation)

**Comment by kevinhwang91** [comment]
> @kevinhwang91 not a bug and also not related to this issue just not sure how else to get this information to you, you might already know don't know if you are on the neovim matrix or watching PRs but [neovim/neovim#19226](https://github.com/neovim/neovim/issues/19226) is in progress which might be interesting for you (just a random FYI not specific motivation)

Thanks for your info. I read the source code before I release this plugin. I think it's not worth doing this in the core if the core team wants to borrow code from Vim.

But an effective API to add folds may help others, but not me, I have already used FFI to boost.

**Comment by no-more-secrets** [comment]
@kevinhwang91  I took a look at the examples, but I still don't quite understand how to use this feature to remove the last `}` on the last line... can someone post an example?  The example in the example.lua file just prints some things.

**Comment by kevinhwang91** [comment]
> @kevinhwang91 I took a look at the examples, but I still don't quite understand how to use this feature to remove the last `}` on the last line... can someone post an example? The example in the example.lua file just prints some things.

https://github.com/kevinhwang91/nvim-ufo/issues/130

**Comment by gzagatti** [comment]
@no-more-secrets 

I manage to put something together that shows the bottom line using the provided snippet:

```lua
require'ufo'.setup({
  enable_get_fold_virt_text = true,
  fold_virt_text_handler = function(virtText, lnum, endLnum, width, truncate, ctx)
    -- include the bottom line in folded text for additional context
    local suffix = ' ⋯ '
    local sufWidth = vim.fn.strdisplaywidth(suffix)
    local targetWidth = width - sufWidth
    local curWidth = 0
    table.insert(virtText, {suffix, 'Folded'})
    local endVirtText = ctx.get_fold_virt_text(endLnum)
    for _, chunk in ipairs(endVirtText) do
      local chunkText = chunk[1]
      local chunkWidth = vim.fn.strdisplaywidth(chunkText)
      if targetWidth > curWidth + chunkWidth then
        table.insert(virtText, chunk)
      else
        chunkText = truncate(chunkText, targetWidth - curWidth)
        local hlGroup = chunk[2]
        table.insert(virtText, {chunkText, hlGroup})
        chunkWidth = vim.fn.strdisplaywidth(chunkText)
        -- str width returned from truncate() may less than 2nd argument, need padding
        if curWidth + chunkWidth < targetWidth then
          suffix = suffix .. (' '):rep(targetWidth - curWidth - chunkWidth)
        end
        break
      end
      curWidth = curWidth + chunkWidth
    end
    return virtText
  end,
})
```

**Comment by shehryar49** [comment]
Hi, Was this feature added? What's the best way to do it today as of 2025
![20250109_18h21m25s_grim](https://github.com/user-attachments/assets/479b0485-37aa-437b-9758-7d6cdf624331)
I want the ending bracket '}' to appear at the same line right after the "..."
Thanks

**Comment by kevinhwang91** [comment]
> Hi, Was this feature added? What's the best way to do it today as of 2025 ![20250109_18h21m25s_grim](https://private-user-images.githubusercontent.com/28148085/401554554-479b0485-37aa-437b-9758-7d6cdf624331.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY3NjAzNTYsIm5iZiI6MTczNjc2MDA1NiwicGF0aCI6Ii8yODE0ODA4NS80MDE1NTQ1NTQtNDc5YjA0ODUtMzdhYS00MzdiLTk3NTgtN2Q2Y2RmNjI0MzMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTEzVDA5MjA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyOWJmNWFhMjg5MmU4NjAxNDNiMjRkZGI5MzBmOGYzODIyYzQxYjRkOTc3MGM3MjA2OWIwNDZlZDkwOTM3NzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-1WL6HNXfO6ps_GcOTuj7IkPHiBJk3ttcPccuqgzBRg) I want the ending bracket '}' to appear at the same line right after the "..." Thanks

Have you seen #130 ?

**Comment by laxino23** [comment]
is there a way to get the last line highlight config as well just like the the first line?
