### ISSUE TITLE
#262 breaks the plugin on neovim v0.10.2

### ISSUE THREAD

**Issue by WieeRd** [kevinhwang91/nvim-ufo#263]
### Neovim version (nvim -v | head -n1)

NVIM v0.10.2

### Operating system/version

Arch Linux

### How to reproduce the issue

Have revision ad23f9000baecf954492b68cf2b63ad310a579ed (#262) of `nvim-ufo` installed and `setup()` on Neovim v0.10.2 and below.

### Expected behavior

The plugin remains backwards compatible and does not break.

### Actual behavior

Upon startup and opening a new buffer, this error message pops up every time.

```
Error executing vim.schedule lua callback: UnhandledPromiseRejection with the reason:
...share/nvim/lazy/nvim-ufo/lua/ufo/provider/treesitter.lua:47: attempt to index local 'start_node' (a nil value)
stack traceback:
        ...share/nvim/lazy/nvim-ufo/lua/ufo/provider/treesitter.lua:47: in function 'from_nodes'
        ...share/nvim/lazy/nvim-ufo/lua/ufo/provider/treesitter.lua:109: in function '(for generator)'
        ...share/nvim/lazy/nvim-ufo/lua/ufo/provider/treesitter.lua:130: in function 'getFoldMatches'
        ...share/nvim/lazy/nvim-ufo/lua/ufo/provider/treesitter.lua:146: in function 'fn'
        /usr/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:491: in function 'for_each_tree'
        ...share/nvim/lazy/nvim-ufo/lua/ufo/provider/treesitter.lua:141: in function 'getCpatureMatchesRecursively'
        ...share/nvim/lazy/nvim-ufo/lua/ufo/provider/treesitter.lua:176: in function 'mainFunc'
        ...local/share/nvim/lazy/nvim-ufo/lua/ufo/provider/init.lua:36: in function <...local/share/nvim/lazy/nvim-ufo/lua/ufo/provider/init.lua:35>
stack traceback:
        [C]: in function 'error'
        ...ieerd/.local/share/nvim/lazy/promise-async/lua/async.lua:90: in function 'await'
        ...rd/.local/share/nvim/lazy/nvim-ufo/lua/ufo/fold/init.lua:34: in function <...rd/.local/share/nvim/lazy/nvim-ufo/lua/ufo/fold/init.lua:24>
```

This behavior cannot be observed in the parent commit, 95cbe2e99901135704aabdc8732d722cf68b12c9.

@zhu was this intentional? v0.10.2 is the current latest stable release of Neovim and neovim/neovim#30193 mentioned in #247 isn't included in it. I think `nvim-ufo` should remain backwards compatible at least until v0.11 comes out.

**Comment by kevinhwang91** [comment]
Reverted

**Comment by kevinhwang91** [comment]
@WieeRd Could you test the https://github.com/kevinhwang91/nvim-ufo/pull/264?
