### ISSUE TITLE
 UnhandledPromiseRejection  for neogit commits

### ISSUE THREAD

**Issue by zbindenren** [kevinhwang91/nvim-ufo#29]
### Neovim version (nvim -v | head -n1)

NVIM v0.7.2

### Operating system/version

arch linux

### How to reproduce the issue

1. commiting a message with neogit

### Expected behavior

No error.

### Actual behavior

I still get the error:

```
error executing vim.schedule lua callback: UnhandledPromiseRejection with the reason:                                                                           
{ ["code"] = 0, ["message"] = stat /home/rz/repos/gitlab.pnet.ch/linux/ces/agent/.git/NEOGIT_COMMIT_EDITMSG: no such file or ```

Even with the following configuration:

local ftMap = {
	vim = "indent",
	git = "",
	NEOGIT_COMMIT_EDITMSG = "",
}

``` lua
-- global handler
ufo.setup({
	fold_virt_text_handler = handler,
	provider_selector = function(bufnr, filetype)
		-- return a string type use internal providers
		-- return a string in a table like a string type
		-- return empty string '' will disable any providers
		-- return `nil` will use default value {'lsp', 'indent'}
		return ftMap[filetype]
	end,
})
```

Not sure what I am doing wrong.

**Comment by zbindenren** [comment]
[ufo.log.gz](https://github.com/kevinhwang91/nvim-ufo/files/9010380/ufo.log.gz)

**Comment by kevinhwang91** [comment]
mul clients issue. Thanks, I should add a simple selector.

**Comment by kevinhwang91** [comment]
No idea why your `.../NEOGIT_COMMIT_EDITMSG` file will ask `gopls`, this buffer shouldn't be attached, may something is wrong with your neogit config.

`NeogitCommitMessage` as ft instead

**Comment by stevanmilic** [comment]
@kevinhwang91 I'm getting a similar error message:
```
Error executing vim.schedule lua callback: UnhandledPromiseRejection with the reason:
.../site/pack/packer/start/nvim-ufo/lua/ufo/fold/buffer.lua:192: Invalid buffer id: 1
```

by disabling all the providers:
```lua
require("ufo").setup({
    open_fold_hl_timeout = 0,
    provider_selector = function(bufnr, filetype)
        -- return empty string '' will disable any providers
        return ''
    end
})

```

**Comment by kevinhwang91** [comment]
@stevanmilic fixed now. but not relate to this issue. `UnhandledPromiseRejection` means throwing errors during promise body.

**Comment by kevinhwang91** [comment]
ping me if has new info
