### ISSUE TITLE
How to keep the following curly braces after code folding

### ISSUE THREAD

**Issue by ShiChenCong** [kevinhwang91/nvim-ufo#43]
### Feature description

![image](https://user-images.githubusercontent.com/22486446/177456414-a75cbbd4-8cd8-4396-9556-7299f33bd4e2.png)

### Describe the solution you'd like

  keep the following curly braces after code folding

**Comment by kevinhwang91** [comment]
What's your point?

Appending `}` to `{ ...`?

**Comment by ShiChenCong** [comment]
hmm. found it's alreay working as i wish
