### ISSUE TITLE
Allow to configure open_fold_hl group(UfoFoldedBg)

### ISSUE THREAD

**Issue by vatosarmat** [kevinhwang91/nvim-ufo#50]
### Feature description

Allow to configure highlight color which is applied when opening folds(`UfoFoldedBg`)
Currently it is forced to be same as `Folded` background

### Describe the solution you'd like

change 
```cmd(('hi UfoFoldedBg guibg=#%x'):format(hl.background))``` 
to
```cmd(('hi default UfoFoldedBg guibg=#%x'):format(hl.background))``` 

### Additional context

Thanks you for the great plugin!

**Comment by kevinhwang91** [comment]
Good idea.
