### ISSUE TITLE
Strange foldtext suffix with tree-sitter

### ISSUE THREAD

**Issue by stevanmilic** [kevinhwang91/nvim-ufo#52]
### Neovim version (nvim -v | head -n1)

head

### Operating system/version

macOS 12.4

### How to reproduce the issue

![image](https://user-images.githubusercontent.com/6879030/179217520-0ff362b1-3676-4734-a7f6-b28af767f062.png)

I'm getting this strange output from time-to-time with tree-sitter provider. I'm not entirely sure if it's related to that provider only, since that's the only I'm using tho. Reloading the buffer makes the folded text correct again.

### Expected behavior

For fold text to not have occasional strange suffix.

### Actual behavior

Fold text sometimes gets buggy.

**Comment by kevinhwang91** [comment]
Look like the buffer is detached and can't be synced. 

Make sure `lua =require'ufo.bufmanager'.buffers[vim.api.nvim_get_current_buf()].attached` output `true`

**Comment by kevinhwang91** [comment]
https://github.com/kevinhwang91/nvim-ufo/blob/d51f533c8deafa9cd394ecdb032e0274bac5917a/lua/ufo/main.lua#L127-L133 only output the text to overlap the raw text. Make true that the function works fine as you encounter the issue.

**Comment by stevanmilic** [comment]
hmm could be, I've been using `pretty-fold` before ufo, but I'm not sure how could it affect the `foldtext` since it's deleted, could be that smth is cached tho

**Comment by stevanmilic** [comment]
Got it, thanks for quickly resolving this issues 💪🏻
