### ISSUE TITLE
module 'ufo' not found

### ISSUE THREAD

**Issue by hronro** [kevinhwang91/nvim-ufo#56]
### Neovim version (nvim -v | head -n1)

NVIM v0.7.2

### Operating system/version

Arch Linux

### How to reproduce the issue

`cat mini.lua`
```lua
vim.o.packpath = '~/.local/share/nvim/site'
require'packer'.startup(function()
  use {
    'kevinhwang91/nvim-ufo',
    requires = 'kevinhwang91/promise-async',
    setup = function ()
      vim.o.foldcolumn = '1'
      vim.o.foldlevel = 99
      vim.o.foldlevelstart = -1
      vim.o.foldenable = true

      vim.keymap.set('n', 'zR', require'ufo'.openAllFolds)
      vim.keymap.set('n', 'zM', require'ufo'.closeAllFolds)
    end,
    config = function ()
      require'ufo'.setup({
        provider_selector = function (bufnr, filetype, buftype)
            return {'treesitter', 'indent'}
        end
      })
    end,
  }
end
```
`nvim --clean -u mini.lua`

### Expected behavior

Should works

### Actual behavior

Got error:

```
module 'ufo' not found
```

**Comment by kevinhwang91** [comment]
May packer.nvim issue. `PackerSync` before `PackerUpdate`

**Comment by hronro** [comment]
@kevinhwang91 I do use `PackerSync` instead of `PackerUpdate`.

**Comment by hronro** [comment]
Should I use `require'ufo'.openAllFolds` or `require'nvim-ufo'.openAllFolds`?

**Comment by kevinhwang91** [comment]
Sorry, It's `PackerCompile` not `PackerSync`.

**Comment by hronro** [comment]
@kevinhwang91 

Same.

And AFAIN, `PackerCompile` basically equals to `PackerCompile` + `PackerUpdate`.

**Comment by hronro** [comment]
@kevinhwang91 Would you mind reopen the issue, since using `PackerCompile` and `PackerUpdate` didn't fix the issue.

**Comment by kevinhwang91** [comment]
Not ufo issue, please `:h :packadd`

**Comment by soifou** [comment]
@hronro the `ufo` lua module is not yet available in Packer `setup()` but it is in `config()`, so you have 2 choices : either you  move both of the keymaps to your `config()` or add `module = "ufo"` in your Packer spec.
