### ISSUE TITLE
error showing while opening uncommon file extensions

### ISSUE THREAD

**Issue by edward-s** [kevinhwang91/nvim-ufo#61]
### Neovim version (nvim -v | head -n1)

0.8 nightly

### Operating system/version

macOS 12

### How to reproduce the issue

Plugin and fold works great for common file types (javascript, json, html etc)

but, on opening a file of a uncommon/unknown extension (i.e: `.huskyrc`, `.dockerignore`),  it immediately errors out with the message below

### Expected behavior

I don't expect the fold to work on these files, but at least the plugin should not throw error

### Actual behavior

```
Error executing vim.schedule lua callback: UnhandledPromiseRejection with the reason:
...re/nvim/site/pack/packer/start/nvim-ufo/lua/ufo/fold.lua:112: ...ck/packer/start/nvim-ufo/lua/ufo/provider/treesitter.lua:95: UfoFallbackException
stack traceback:
        ...re/nvim/site/pack/packer/start/nvim-ufo/lua/ufo/fold.lua:45: in function <Anonymous:26>
```

**Comment by kevinhwang91** [comment]
can't reproduce, please provider min.lua

**Comment by kevinhwang91** [comment]
I guess you set 
```lua
        provider_selector = function(bufnr, filetype, buftype)
            return {'lsp', 'treesitter'}
        end,
```

`lsp` and `treesitter` are `main` provider, `fallback` provider is only `indent`  for now.

**Comment by edward-s** [comment]
setting to just 
```
provider_selector = function()
   return {  "indent" }
end,
```
works for me

was looking at the line of code that was throwing error in treesitter.lua
```
local parser = parsers.get_parser(bufnr)
    if not parser then
      hasProviders[ft] = false
      error('UfoFallbackException')
end
```
isn't the issue my `.dockerignore` file has no associated TS parser so it throws, is that error throwing necessary
