### ISSUE TITLE
UnhandledPromiseRejection

### ISSUE THREAD

**Issue by juridiener** [kevinhwang91/nvim-ufo#65]
### Neovim version (nvim -v | head -n1)

Nvim 7.0

### Operating system/version

macOS

### How to reproduce the issue

Hello, if i open neovim i get this error message.
...
<img width="1792" alt="Screenshot 2022-08-15 at 10 04 05" src="https://user-images.githubusercontent.com/92093874/184599158-ad72ff3c-829c-4ec4-a46b-277fad9e1804.png">

### Expected behavior

No errors.

### Actual behavior

Not possible to use neovim.

**Comment by kevinhwang91** [comment]
https://github.com/kevinhwang91/nvim-ufo/issues/61

https://github.com/kevinhwang91/nvim-ufo/issues/63
