### ISSUE TITLE
Control Side line UI

### ISSUE THREAD

**Issue by prudnikovsv** [kevinhwang91/nvim-ufo#67]
### Feature description

As a client I would like to have ability to control colours and look of side bar of folds.
* Background (In case if I would like to make it transparent)
* Show / Hide side bar of folds
* Show or Hide fold level of side bar
* Change icons of side bar

Side bar:
![image](https://user-images.githubusercontent.com/8155269/185193540-0b0c4434-8b31-4ed4-adcb-2a575b480c0f.png)

### Describe the solution you'd like

Create separate configuration object for UI: eg change higlights, and other ui configuration for flexibility

**Comment by kevinhwang91** [comment]
There're some limitations to the UI.
https://github.com/kevinhwang91/nvim-ufo/issues/4

This feature is the closest to what you want, ufo should make sure the regression of perf is acceptable for customized UI components, need a lot of time to explore.
https://github.com/kevinhwang91/nvim-ufo/issues/24
