### ISSUE TITLE
documentation required: folding all on initial open

### ISSUE THREAD

**Issue by rbutera** [kevinhwang91/nvim-ufo#69]
### Feature description

After I installed nvim-ufo using the treesitter method and the suggested settings, all files opened in nvim are automatically folded to the max when initially opened.

nvim-ufo documentation does not make this clear whether or not this is expected behaviour, and/or whether this is configurable.	

### Describe the solution you'd like

This issue should be clarified in documentation

**Comment by kevinhwang91** [comment]
> Using a provider of ufo, must set a large value for foldlevel, this is the limitation of foldmethod=manual. A small value may close fold automatically if the fold ranges updated
