### ISSUE TITLE
foldlevel changed by `zR`, `zM` sometime buggy

### ISSUE THREAD

**Issue by kevinhwang91** [kevinhwang91/nvim-ufo#7]
### Neovim version (nvim -v | head -n1)

NVIM v0.7.0

### Operating system/version

ArchLinux

### How to reproduce the issue

```lua
local function level1()
    local function level2()
        |
    end
end
```
1. type `zR`, `foldlevel` become 2
2. change buffer becomes:
```lua
local function level1()
    local function level2()
        if true then
            print('level3')
        end
    end
end
```
and enter normal mode, folds have applied, level3 is closed automatically.

### Expected behavior

level 3 fold keeps open.

### Actual behavior

![image](https://user-images.githubusercontent.com/17562139/174440129-63d826f6-4d29-4e47-9b8e-460939e3842a.png)

**Comment by kevinhwang91** [comment]
Look like should mock `zR` and `zM` behavior but keep `foldlevel` value. Vim have `v:count1 + zr` and `v:count1 + zm` to change foldlevel,  not bad to remap `zR` and `zM`.

**Comment by ziontee113** [comment]
Sorry to ask this but how should I remap `zR` and `zM`? I know very little vimscript and I don't know how to use `v:count1 + zr`.

**Comment by kevinhwang91** [comment]
wow, not easy to do, let me think about how to conquer this buggy.

**Comment by kevinhwang91** [comment]
Please update code.
use `require('ufo').openAllFolds()`  and `require('ufo').closeAllFolds()` instead. For now, I leave this issue.

**Comment by ziontee113** [comment]
Thank you, it's working :+1:

**Comment by ranjithshegde** [comment]
Could this also be extended for `za` and `zo`?

here is the scenario 
Step 1: open fold using any way other than `zr` like `za` or `zo`
Step 2: Insert enter and do stuff
step 3: Insert leave.
Result, just all folds have closed and i cant see what I just edided so that I can navigate

I think `za` and `zr` are important because they only open/close folds under the current cursor position instead of operating onl all folds of the same level in the whole window/buffer

**Comment by kevinhwang91** [comment]
> 

Sure, will be done tonight.

**Comment by kevinhwang91** [comment]
> 

I think I misunderstand something. Open an new issue please.

**Comment by ziontee113** [comment]
Hi man it was stable before but now when I use `zM` using `require('ufo').closeAllFolds()` the terminal freezes (crash).

**Comment by kevinhwang91** [comment]
> Hi man it was stable before but now when I use `zM` using `require('ufo').closeAllFolds()` the terminal freezes (crash) if the `foldmethod=marker`, it works fine with buffers with `foldmethod=manual`

Thanks, update the code please
