### ISSUE TITLE
YAML folds not working

### ISSUE THREAD

**Issue by windowsrefund** [kevinhwang91/nvim-ufo#72]
### Neovim version (nvim -v | head -n1)

0.7.2

### Operating system/version

Who cares

### How to reproduce the issue

Open any YAML file

### Expected behavior

Expect folds to work

### Actual behavior

![Screenshot_2022-09-01_23-51-06](https://user-images.githubusercontent.com/512222/188055564-85ea9f95-1750-4727-b863-687a83f4ab19.png)

Tried every configuration example I can find on this site including #21 but nothing works.

**Comment by kevinhwang91** [comment]
```lua
-- Option 2: nvim lsp as LSP client
-- Tell the server the capability of foldingRange,
-- Neovim hasn't added foldingRange to default capabilities, users must add it manually
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.foldingRange = {
    dynamicRegistration = false,
    lineFoldingOnly = true
}
```

**Comment by windowsrefund** [comment]
That does not work. Have you opened a yaml file yourself with that setup (with yamlls installed and attached to the buffer)?

**Comment by kevinhwang91** [comment]
Work for me. Debug yourself to make sure `capabilities.textDocument` contains `foldingRange`.

**Comment by msva** [comment]
Acttually, I had exactly same error with exactly same yaml langserver.


Problem was exactly in the fact that I missed to pass `capabilities` to exactly that langserver.

FYI, @windowsrefund

**Comment by costa-simulatedreality** [comment]
I have added this lines of code to include the capabilities in the available language servers (this file is in my `.config/lvim/after/plugin/nvim-ufo.lua`)

```
vim.o.foldcolumn = '1' -- '0' is not bad
vim.o.foldlevel = 99 -- Using ufo provider need a large value, feel free to decrease the value
vim.o.foldlevelstart = 99
vim.o.foldenable = true
vim.o.fillchars = [[eob: ,fold: ,foldopen:,foldsep: ,foldclose:]]

-- Tell the server the capability of foldingRange,
-- Neovim hasn't added foldingRange to default capabilities, users must add it manually
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.foldingRange = {
    dynamicRegistration = false,
    lineFoldingOnly = true
}
local language_servers = require("lspconfig").util.available_servers() -- or list servers manually like {'gopls', 'clangd'}
for _, ls in ipairs(language_servers) do
    require('lspconfig')[ls].setup({
        capabilities = capabilities
        -- you can add other fields for setting up lsp server in this table
    })
end

local builtin = require("statuscol.builtin")
require("statuscol").setup({
  relculright = true,
  segments = {
    { text = { builtin.foldfunc }, click = "v:lua.ScFa" },
    { text = { "%s" }, click = "v:lua.ScSa" },
    { text = { builtin.lnumfunc, " " }, click = "v:lua.ScLa" },
  },
})

require('ufo').setup()
```

But for some reason I keep getting this "Request textDocument/foldingRange failed with message: Cannot read properties of undefined (reading 'lineFoldingOnly')" error message every time I open a yaml file. 
When I do check if the ymlls server is available, it in fact is!
![image](https://github.com/kevinhwang91/nvim-ufo/assets/126523657/aa7f17f6-d055-417d-aa7d-0e53747fb665)


How can I check if the capability has been added to my ls on runtime (i.e. after lunarvim has gone through the whole configuration setup) ?

**Comment by kapral18** [comment]
@kevinhwang91 this is not fixed, passing capabilities doesn't fix the issue, reopen please.

**Comment by Kumm-Kai** [comment]
I've also experienced this issue. For me, it was caused by initializing ufo before my LSPs.
What I'm now still confused about is why this was only happening with `yamlls` and not with other LSPs like `gopls` or `lua_ls`. For the other LSPs, `:UfoInspect` always said `Selected provider: lsp` and folding was working as expected.

Would be awesome if someone knows what's the reason behind that 🙂
