### ISSUE TITLE
decide preview position by fold kind 

### ISSUE THREAD

**Issue by hleft** [kevinhwang91/nvim-ufo#73]
### Feature description

`peekFoldedLinesUnderCursor` will open preview window after cursor , so I can see function comment and function content , 

but if use `CocAction('fold', 'comment')`, then preview comment will overlap with function, can't see comment and function at the same time

### Describe the solution you'd like

support if fold comment, preview before cursor, instead always preview after cursor

**Comment by kevinhwang91** [comment]
Yes, I also need this feature.

**Comment by kevinhwang91** [comment]
Do you have any suggestions to handle the bottom border for this feature?

**Comment by hleft** [comment]
@kevinhwang91  I don't know the relationship between this feature and the bottom border...

**Comment by kevinhwang91** [comment]
Done. It's hard coding for now because I can't come up with other use cases.

**Comment by zdmgmail** [comment]
> Done. It's hard coding for now because I can't come up with other use cases.

How to config it work? I update then use `CocAction('fold', 'comment')` and preview still before cursor

**Comment by hleft** [comment]
> Done. It's hard coding for now because I can't come up with other use cases.

How to config it work? I update then use CocAction('fold', 'comment') and preview still after cursor

**Comment by kevinhwang91** [comment]
Make sure `UfoInspect` output `Selected provider: lsp` and peek folded comment lines.

**Comment by kevinhwang91** [comment]
The `trace` action is broken for this, I'm working on it.

**Comment by hleft** [comment]
@kevinhwang91  Now preview comment will not overlap, but  preview function content will overlap one line comment

**Comment by kevinhwang91** [comment]
I can't get your point, please explain clearly. Maybe a screenshot or a video should help.

**Comment by hleft** [comment]
@kevinhwang91 

![1](https://user-images.githubusercontent.com/89069008/188551897-3498b8d8-9be9-4265-acac-f6363dca27a9.png)

preview comment, not overlap function content
![2](https://user-images.githubusercontent.com/89069008/188551916-11787947-ab6b-4005-956a-c912d2ec52b9.png)

preview function content, overlap one line comment
![3](https://user-images.githubusercontent.com/89069008/188552213-cad7ed31-1af3-4ca8-a28b-525a0ae35929.png)

hope preview content not overlap comment

**Comment by kevinhwang91** [comment]
It's expected, depending on your border.

**Comment by hleft** [comment]
@kevinhwang91  Well, some want to have borders and not overlapping ...

**Comment by kevinhwang91** [comment]
Normal folded lines need to reduce redraw if fire `trace` action.
I don't think it will often fire the `trace` action under the folded lines with `comment`  kind.
