### ISSUE TITLE
Compatibility with hop.nvim

### ISSUE THREAD

**Issue by meijieru** [kevinhwang91/nvim-ufo#80]
### Feature description

Currently, when folded, `HopLineStartAC` doesn't have any markers
![image](https://user-images.githubusercontent.com/9511136/190527875-f23d86a2-5276-4956-9198-101f8bc90978.png)
However, `HopLineAC` works
![image](https://user-images.githubusercontent.com/9511136/190527923-78b2852d-7b40-4793-af96-93f9b3c6826c.png)

### Describe the solution you'd like

Both `HopLineStartAC` & `HopLineAC` should have markers for jumping.

**Comment by kevinhwang91** [comment]
You should open the issue at hop.nvim to support markers for folded lines. Look like hop.nvim has skipped folded lines after a PR.
