### ISSUE TITLE
Need ufo.preview.winbar file

### ISSUE THREAD

**Issue by rhcher** [kevinhwang91/nvim-ufo#84]
### Neovim version (nvim -v | head -n1)

NVIM v0.8.0-dev-1194-ga80ab395a-dirty

### Operating system/version

wsl2 Arch

### How to reproduce the issue

`cat mini.lua`
```lua
-- Use Vim packages install the plugin, also work with some plugins manager such as packer.nvim
vim.o.packpath = '~/.local/share/nvim/site'
vim.cmd('packadd promise-async')
vim.cmd('packadd nvim-ufo')

-- Setting
vim.o.foldcolumn = '1'
vim.o.foldlevel = 99
vim.o.foldlevelstart = -1
vim.o.foldenable = true

local ufo = require('ufo')
ufo.setup()
vim.keymap.set('n', 'zR', ufo.openAllFolds)
vim.keymap.set('n', 'zM', ufo.closeAllFolds)
```
`nvim --clean +'so mini.lua'`

### Expected behavior

Have this file

### Actual behavior

No such file

**Comment by dhruvinsh** [comment]
Yes, ufo/preview/winbar.lua is misisng. 

I just reveiew the commit.

**Comment by kevinhwang91** [comment]
Damn, you are so fast.
