### ISSUE TITLE
Hide the fold number

### ISSUE THREAD

**Issue by DeeGeeMan** [kevinhwang91/nvim-ufo#86]
### Feature description

How do I hide the fold number in the column?  I am using `nvim 0.8`.

Example:
<img width="1002" alt="fold-numbes" src="https://user-images.githubusercontent.com/21670040/194779162-87af390f-5ea1-41f7-a5cf-fef6dfe168b9.png">

### Describe the solution you'd like

No numbers in the fold column.

**Comment by kevinhwang91** [comment]
https://github.com/kevinhwang91/nvim-ufo/issues/4
