### ISSUE TITLE
Indent fallback not working?

### ISSUE THREAD

**Issue by nwaywood** [kevinhwang91/nvim-ufo#87]
### Neovim version (nvim -v | head -n1)

NVIM v0.8.0

### Operating system/version

macOS 12.5

### How to reproduce the issue

1. Use this ufo setup from the readme
```lua
vim.opt.foldenable = true
vim.opt.foldlevel = 99
vim.opt.foldlevelstart = 99

require("ufo").setup({
	provider_selector = function(bufnr, filetype, buftype)
		return { "treesitter", "indent" }
	end,
})
```
2. Navigate to an indented section of code that doesn't have a treesitter fold
3. Try and fold with `zc`

### Expected behavior

Since no treesitter fold is found, ufo should fallback to indent folding and fold the code by indent 

### Actual behavior

The message `E490: No fold found` is displayed

**Comment by kevinhwang91** [comment]
Can't reproduce it, check out your `shiftwidth`, please.

**Comment by kevinhwang91** [comment]
> Maybe that should be added to the readme?

I don't think it's necessary for Vimer, without a correct `shiftwidth` value, insert a newline is always buggy.

Does the correct `shiftwidth` work for you?

**Comment by nwaywood** [comment]
@kevinhwang91 I don't think my `shiftwidth` value is the issue. I had it set to 2 and it didn't work, I just tried `shiftwidth=4` and the bug is present with both values.

Do you have any other ideas what the issue might be?

**Comment by nwaywood** [comment]
If it's relevant. I am experiencing this bug in a Scala file

**Comment by kevinhwang91** [comment]
Make sure that `UfoInspect` output `Selected provider: indent`.

Trim the issue file and post it here.

**Comment by nwaywood** [comment]
@kevinhwang91 oh wait maybe I misunderstood how the fallback works. I am in a file that has some treesitter folds but it isn't able to fold some sections of the file, I thought it is meant to fallback if there is a section of code that treesitter isn't able to fold. Is that not how it works? Does the fallback only work at the file level?

<img width="435" alt="image" src="https://user-images.githubusercontent.com/3773641/195743545-0d723730-a1db-46c0-9418-99eff7d08c7b.png">

**Comment by kevinhwang91** [comment]
> Does the fallback only work at the file level?

All providers work at the file level. If you want them to work together, you must write an external provider for `provider_selector`, `doc/example` may help you understand it.

**Comment by nwaywood** [comment]
Ah gotcha! Thanks for the help, sorry for my misunderstanding!
