### ISSUE TITLE
A more compact option to set the folding text

### ISSUE THREAD

**Issue by Karmenzind** [kevinhwang91/nvim-ufo#88]
### Feature description

The lua config file is too long. Now I have to add 37 more lines to set the folding text. Please provide a more compact option to set the folding text. Like this:

```
default_folding_format = '{lines} custom text {start-line} blabla'
```

Or a function like the builtin `foldtext()` in vim which is only about the string itself.

Thanks a lot.

### Describe the solution you'd like

Maybe you can wrap the [handler function example](https://github.com/kevinhwang91/nvim-ufo#customize-fold-text) as a default folding template accepting a format string, and provide an option to set it.
It will be good enough for many people and we only need to write one line.

**Comment by kevinhwang91** [comment]
There are many context need to expose to users.

`foldtext()` only depend on string. but the content of the fold is actually virt_text that depends on a list of `{text, highlight }` . 
The color folds are not the standard of ufo, ufo should respect virt_text with extmarks api.

If you think 37 loc is large for you, I think the default style is not bad compared with the raw `foldtext()`.
