### ISSUE TITLE
Single-line folds aren't handled

### ISSUE THREAD

**Issue by romgrk** [kevinhwang91/nvim-ufo#9]
### Neovim version (nvim -v | head -n1)

0.8.0-dev

### Operating system/version

archlinux

### How to reproduce the issue

Open a file with single line folds and close all folds.

```lua
local dict = {
    a = 1,
    b = {
        c = 2,
    },
    d = { e = 3 }
}
```

### Expected behavior

All folds use the ufo style.

### Actual behavior

![image](https://user-images.githubusercontent.com/1423607/174467965-6043be61-48f4-40b4-b585-e60e058c608b.png)

**Comment by kevinhwang91** [comment]
Expected. Show a use case for single fold line please.

**Comment by romgrk** [comment]
None, but it's annoying that some folds have a different style when I close them all.

**Comment by kevinhwang91** [comment]
`set foldminlines=1`  will never close the single folded line.

**Comment by romgrk** [comment]
Got it, thanks.
