### ISSUE TITLE
removing numbers in fold icon column

### ISSUE THREAD

**Issue by NoamMuallem** [kevinhwang91/nvim-ufo#92]
### Neovim version (nvim -v | head -n1)

NVIM v0.8.0

### Operating system/version

macOS Monterey 12.6.1

### How to reproduce the issue

* happens with no extra configuration, only the defaults in the readme
`cat mini.lua`
```lua
-- Use Vim packages install the plugin, also work with some plugins manager such as packer.nvim
vim.o.packpath = '~/.local/share/nvim/site'
vim.cmd('packadd promise-async')
vim.cmd('packadd nvim-ufo')

-- Setting
vim.o.foldcolumn = '1'
vim.o.foldlevel = 99
vim.o.foldlevelstart = -1
vim.o.foldenable = true

local ufo = require('ufo')
ufo.setup()
vim.keymap.set('n', 'zR', ufo.openAllFolds)
vim.keymap.set('n', 'zM', ufo.closeAllFolds)
```
`nvim --clean +'so mini.lua'`

1.
2.
3.
...

### Expected behavior

like in read me only fold icons

### Actual behavior

numbers on the lines where fold is not available
<img width="88" alt="Screen Shot 2022-11-02 at 13 00 29" src="https://user-images.githubusercontent.com/40291455/199410981-5c3e5710-5399-4103-8ee5-b54ad08d9246.png">

**Comment by kevinhwang91** [comment]
https://github.com/kevinhwang91/nvim-ufo/issues/4

**Comment by D00mch** [comment]
If someone finds it and don't want to read 100 comments on #4.

To remove it completely:
`vim.o.foldcolumn = "0"`

To have foldcolumn like in demo video:
`vim.o.fillchars = [[eob: ,fold: ,foldopen:,foldsep: ,foldclose:]]`

**Comment by shalawfatah** [comment]
If someone still looks for an answer, this config in this plugin `statuscol.nvim` removes the numbers while the arrows are still there on the same column:
```
  {
    'luukvbaal/statuscol.nvim',
    opts = function()
      local builtin = require('statuscol.builtin')
      return {
        setopt = true,
        -- override the default list of segments with:
        -- number-less fold indicator, then signs, then line number & separator
        segments = {
          { text = { builtin.foldfunc }, click = 'v:lua.ScFa' },
          { text = { '%s' }, click = 'v:lua.ScSa' },
          {
            text = { builtin.lnumfunc, ' ' },
            condition = { true, builtin.not_empty },
            click = 'v:lua.ScLa',
          },
        },
      }
    end,
  }
```

**Comment by geloman-likes-rust** [comment]
## Simple Solution
I fixed this issue by simply setting `vim.o.foldcolumn = 'auto:9'`. Just read the friendly manual `:h foldcolumn`
![Screenshot from 2024-07-20 at 21:10:31](https://github.com/user-attachments/assets/0179b89e-2633-4410-b49f-99796d7086b4)
