### ISSUE TITLE
automatically folds after deleting newlines between folds

### ISSUE THREAD

**Issue by ipsod** [kevinhwang91/nvim-ufo#94]
### Neovim version (nvim -v | head -n1)

NVIM v0.9.0-dev

### Operating system/version

linux mint 21

### How to reproduce the issue

create text file with multiple levels of folds:

    test
        row
            sub
            sub
        row
            sub
            sub

fold to hide `sub`, but show row  (`set foldlevel=1`, I think)

insert or delete a blank newline between the two `row` folds.  Both inserting and deleting cause it.

editor will now automatically (and undesirably) fold all the way, and hide `row`s

### Expected behavior

fold level should not change because of modification of text

### Actual behavior

The text you're editing gets folded because you edited the text.  Especially troublesome if it folds, then you end up deleting N folded lines instead of the single unfolded line you meant to.

**Comment by kevinhwang91** [comment]
> Using a provider of ufo, must set a large value for foldlevel, this is the limitation of foldmethod=manual. A small value may close fold automatically if the fold ranges updated.

https://github.com/kevinhwang91/nvim-ufo/issues/7
https://github.com/kevinhwang91/nvim-ufo/issues/57
https://github.com/kevinhwang91/nvim-ufo/issues/89

**Comment by ipsod** [comment]
I do have a large foldlevel in my config, as the instructions say.

    vim.o.foldcolumn = '0' -- '0' is not bad
    vim.o.foldlevel = 99 -- Using ufo provider need a large value, feel free to decrease the value
    vim.o.foldlevelstart = 99
    vim.o.foldenable = true


However, I change the foldlevel when editing text with `zM`, `zr`, etc.

Do you mean, this kind of use is not compatible with nvim-ufo?

**Comment by ipsod** [comment]
Ah, I see.  Sorry about that.

Is the config here supposed to restore normal functionality to `zm`, `zM`, `zr`, and `zR`?  https://github.com/kevinhwang91/nvim-ufo#customize-configuration

I copied it directly, and `zm` and `zr` seem to have the same behavior as `zM` and `zR`.

**Comment by kevinhwang91** [comment]
1. number + `zm`.
2.  `zr` is the same as `zM` if the kind is excluded in `close_fold_kinds`.

**Comment by ipsod** [comment]
Is there a way to just increment/deincrement mock-indent-level, to simulate standard behavior?

**Comment by kevinhwang91** [comment]
No, `foldlevel` should keep a large value. Must maintain `your_foldlevel` by yourself. Need to write a script.

```lua
vim.api.nvim_create_autocmd({'WinNew', 'VimEnter'}, {
    pattern = '*',
    callback = function()
        vim.w.my_foldlevel = 20
    end
})

vim.keymap.set('n', 'zr', function()
    vim.w.my_foldlevel = vim.w.my_foldlevel - 1
    require('ufo').closeFoldsWith(vim.w.my_foldlevel)
end)

vim.keymap.set('n', 'zm', function()
    vim.w.my_foldlevel = vim.w.my_foldlevel + 1
    require('ufo').closeFoldsWith(vim.w.my_foldlevel)
end)
```

**Comment by ipsod** [comment]
This seems to be working well.  Need to figure out how to hold it to min of zero (never programmed Lua).  Might also like it to use current cursor position's indent level, if it's not too hard (ie: `vim.w.my_foldlevel = max(vim.w.my_foldlevel, cursor_foldlevel)`.

Thanks for the help!

    vim.api.nvim_create_autocmd({'WinNew', 'VimEnter'}, {
        pattern = '*',
        callback = function()
            vim.w.my_foldlevel = 1
        end
    })

    vim.keymap.set('n', 'zM', function()
        vim.w.my_foldlevel = 0
        require('ufo').closeFoldsWith(vim.w.my_foldlevel)
    end)

    vim.keymap.set('n', 'zR', function()
        vim.w.my_foldlevel = 5
        require('ufo').closeFoldsWith(vim.w.my_foldlevel)
    end)

    vim.keymap.set('n', 'zr', function()
        vim.w.my_foldlevel = vim.w.my_foldlevel + 1
        require('ufo').closeFoldsWith(vim.w.my_foldlevel)
    end)

    vim.keymap.set('n', 'zm', function()
        vim.w.my_foldlevel = vim.w.my_foldlevel - 1

        require('ufo').closeFoldsWith(vim.w.my_foldlevel)
    end)
