### ISSUE TITLE
transparent background for folded lines

### ISSUE THREAD

**Issue by thaiducdung255** [kevinhwang91/nvim-ufo#96]
### Feature description

Hi, I don't know how to set transparent background for folded lines as shown in the below image:

![image](https://user-images.githubusercontent.com/43328993/201893799-a416bc78-4a50-4604-af8f-6f438bf42136.png)

Thank you, I like this plugin so much!

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/43328993/201893910-bd36a610-347c-4e27-9972-e4669fe88127.png)

**Comment by kevinhwang91** [comment]
`hi clear Folded`
