### ISSUE TITLE
Code comments about what example fold_virt_text_handler is doing

### ISSUE THREAD

**Issue by technicalpickles** [kevinhwang91/nvim-ufo#98]
### Feature description

I am just starting out with ufo, and I’m having trouble understanding what exactly the example `fold_virt_text_handler` does, and how it is doing it. From the screenshot and the code, it looks like it’s adding virtual text with the number of lines in the fold?

### Describe the solution you'd like

Some description of what the example customization is doing, and code comments about what some of the inputs / changes are.

**Comment by kevinhwang91** [comment]
Yes, feel free to update the docs :)

**Comment by technicalpickles** [comment]
That helps, thank you!
